/**
 * Proof of Residential Address — who may create it, pinned.
 *
 * Carla's rule (2026-10-06): only Accounting creates this letter. The table holds
 * every type, so the rule lives in the app: the employee form and the employee
 * route read EMPLOYEE_REQUEST_TYPES, never the full list. These scans fail the
 * build if either surface goes back to the full list — the form used to map
 * Object.entries(DOCUMENT_TYPE_LABELS), which would have offered the new type to
 * every employee the moment its label was added.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {
  DOCUMENT_REQUEST_TYPES,
  DOCUMENT_TYPE_LABELS,
  EMPLOYEE_REQUEST_TYPES,
  isEmployeeRequestType,
  isSystemGeneratedType,
} from './types';
import { decideCoeActiveGate } from './coe-admin';
import { ADDRESS_LETTER_GATE_WORDING } from './address-letter';

const read = (rel: string) => fs.readFileSync(path.join(process.cwd(), rel), 'utf8').replace(/\r\n/g, '\n');

test('address is a stored type with a label, generated by the HRIS, and NOT employee-requestable', () => {
  assert.ok(DOCUMENT_REQUEST_TYPES.includes('address'));
  assert.equal(DOCUMENT_TYPE_LABELS.address, 'Proof of Residential Address');
  assert.ok(isSystemGeneratedType('address'), 'its original.pdf is a watermarked draft');
  assert.ok(!EMPLOYEE_REQUEST_TYPES.includes('address'));
  assert.equal(isEmployeeRequestType('address'), false);
  for (const t of ['paystub', 'coe', 'award', 'other']) assert.ok(isEmployeeRequestType(t), t);
});

test('the employee route validates against EMPLOYEE_REQUEST_TYPES, never the full list', () => {
  const src = read('app/api/employee/documents/route.ts');
  assert.match(src, /isEmployeeRequestType\(documentType\)/);
  assert.doesNotMatch(src, /isDocumentRequestType/);
  assert.doesNotMatch(src, /DOCUMENT_REQUEST_TYPES/);
});

test('the employee form lists EMPLOYEE_REQUEST_TYPES, never every label', () => {
  const src = read('src/components/employee/RequestDocumentsTab.tsx');
  assert.match(src, /EMPLOYEE_REQUEST_TYPES\.map\(/);
  assert.doesNotMatch(src, /Object\.(entries|keys)\(DOCUMENT_TYPE_LABELS\)/);
  assert.doesNotMatch(src, /DOCUMENT_REQUEST_TYPES/);
});

test('the Approve path refuses an address row before it touches a signature', () => {
  const src = read('src/lib/documents/requests.ts');
  const start = src.indexOf('export async function signDocumentRequest(');
  assert.ok(start > 0);
  const body = src.slice(start);
  const guard = body.indexOf("row.document_type === 'address'");
  const sig = body.indexOf('getDocumentSignature(approver)');
  assert.ok(guard > 0 && sig > 0 && guard < sig, 'the address guard runs before the signature read');
});

test('the address letter is delivered WITHOUT the certification page (its "submitted by the employee" is false here)', () => {
  const src = read('src/lib/documents/requests.ts');
  const start = src.indexOf('export async function createSignedAddressLetter(');
  const end = src.indexOf('\nexport async function', start + 10);
  assert.ok(start > 0 && end > start);
  assert.doesNotMatch(src.slice(start, end), /stampSignedDocument\(/);
});

test('the address routes are edit-gated on accounting/documents — the Generate COE gate', () => {
  for (const rel of ['app/api/accounting/documents/address/route.ts', 'app/api/accounting/documents/address/preview/route.ts']) {
    const src = read(rel);
    assert.match(src, /requireFeatureEdit\('accounting', 'documents'\)/, rel);
    assert.match(src, /wording: ADDRESS_LETTER_GATE_WORDING/, `${rel} runs the active gate under the letter's name`);
  }
});

test("the active gate's COE wording is unchanged; the letter's names itself", () => {
  const off = { active: false, offBoardedAt: '2026-09-01', offBoardedReason: 'resigned' };
  const coe = decideCoeActiveGate({ status: off, statusError: null });
  assert.equal(coe.ok, false);
  if (!coe.ok) {
    assert.equal(
      coe.rejection.message,
      "This person is not active on the Global Master List (off-boarded 2026-09-01, resigned) — a Certificate of Engagement asserts current engagement, so it can't be issued for them.",
    );
  }
  const absentCoe = decideCoeActiveGate({ status: undefined, statusError: null });
  if (!absentCoe.ok) {
    assert.equal(
      absentCoe.rejection.message,
      'This email is not on the Global Master List — a COE can only be generated for an active GML person.',
    );
  }
  const letter = decideCoeActiveGate({ status: off, statusError: null, wording: ADDRESS_LETTER_GATE_WORDING });
  if (!letter.ok) assert.match(letter.rejection.message, /a Proof of Residential Address letter asserts current engagement/);
  // Fails closed the same way: an errored map is a 500, never "not on the list".
  const broken = decideCoeActiveGate({ status: undefined, statusError: 'boom', wording: ADDRESS_LETTER_GATE_WORDING });
  assert.ok(!broken.ok && broken.rejection.status === 500);
});
