// The cursive faces offered by the signature pad's Type mode.
//
// All six are self-hosted under public/fonts/signature (SIL Open Font License
// 1.1), declared in src/index.css and regenerated by
// scripts/fetch-signature-fonts.mjs. They are NOT pulled from the Google CDN
// the way Inter is (src/index.css:1), and that is a guard rather than a
// preference: canvas 2D does not report a missing font — fillText silently
// falls back to the generic family — so a CDN miss would rasterise and save a
// signature that is not cursive, with no error raised anywhere.
//
// `coversText()` is the second half of the same guard. A face ships a subset,
// so a name carrying a glyph outside it would draw as a blank .notdef box on a
// document that goes to a bank. Same idea as isCoveredBySubset() in
// src/lib/pdf/fonts.ts, and the reason the coverage is stored PER FACE:
// Homemade Apple has no latin-ext, so it alone cannot draw "Łukasz".

export interface SignatureFace {
  /** Stable id — persisted only in component state, never in the database. */
  id: string;
  /** CSS font-family, matching the @font-face declarations in src/index.css. */
  family: string;
  /** Picker label. */
  label: string;
  /** One-word character note, shown under the preview. */
  note: string;
  /**
   * Nominal size hint only. The renderer MEASURES the drawn ink and fits it to
   * the raster, so a wrong value here costs a little fitting precision and
   * cannot produce a mis-sized signature. Faces differ enormously in how much
   * of the em they use — Homemade Apple draws roughly twice the height of
   * Great Vibes at the same font-size.
   */
  sizeHint: number;
  /** unicode-range strings, verbatim from the shipped @font-face blocks. */
  ranges: readonly string[];
}

const LATIN =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

const LATIN_EXT =
  'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF';

/** Picker order: formal → casual, so the most document-appropriate is first. */
export const SIGNATURE_FACES: readonly SignatureFace[] = [
  {
    id: 'great-vibes',
    family: 'Great Vibes',
    label: 'Great Vibes',
    note: 'Formal copperplate',
    sizeHint: 1,
    ranges: [LATIN, LATIN_EXT],
  },
  {
    id: 'allura',
    family: 'Allura',
    label: 'Allura',
    note: 'Flourished script',
    sizeHint: 1,
    ranges: [LATIN, LATIN_EXT],
  },
  {
    id: 'sacramento',
    family: 'Sacramento',
    label: 'Sacramento',
    note: 'Fine monoline',
    sizeHint: 1,
    ranges: [LATIN, LATIN_EXT],
  },
  {
    id: 'dancing-script',
    family: 'Dancing Script',
    label: 'Dancing Script',
    note: 'Rounded and casual',
    sizeHint: 0.88,
    ranges: [LATIN, LATIN_EXT],
  },
  {
    id: 'caveat',
    family: 'Caveat',
    label: 'Caveat',
    note: 'Everyday handwriting',
    sizeHint: 0.95,
    ranges: [LATIN, LATIN_EXT],
  },
  {
    id: 'homemade-apple',
    family: 'Homemade Apple',
    label: 'Homemade Apple',
    note: 'Pen on paper',
    sizeHint: 0.62,
    // No latin-ext subset is published for this face — see coversText().
    ranges: [LATIN],
  },
];

export function faceById(id: string): SignatureFace | null {
  return SIGNATURE_FACES.find((f) => f.id === id) ?? null;
}

/** `"Great Vibes", cursive` — the generic keyword is a last-resort so text is
 *  never invisible, and is exactly what the load check exists to catch. */
export function fontStack(face: SignatureFace): string {
  return `'${face.family}', cursive`;
}

interface Range {
  from: number;
  to: number;
}

const RANGE_CACHE = new Map<string, Range[]>();

function parseRanges(spec: string): Range[] {
  const cached = RANGE_CACHE.get(spec);
  if (cached) return cached;
  const out: Range[] = [];
  for (const part of spec.split(',')) {
    const token = part.trim().replace(/^U\+/i, '');
    if (!token) continue;
    const [lo, hi] = token.split('-');
    const from = Number.parseInt(lo, 16);
    if (!Number.isFinite(from)) continue;
    const to = hi ? Number.parseInt(hi, 16) : from;
    out.push({ from, to: Number.isFinite(to) ? to : from });
  }
  RANGE_CACHE.set(spec, out);
  return out;
}

/** Every code point the face's shipped subsets can draw. */
export function faceCovers(face: SignatureFace, codePoint: number): boolean {
  for (const spec of face.ranges) {
    for (const r of parseRanges(spec)) {
      if (codePoint >= r.from && codePoint <= r.to) return true;
    }
  }
  return false;
}

/**
 * The characters in `text` this face cannot draw, de-duplicated and in order of
 * first appearance. Empty means safe to rasterise.
 *
 * Spaces are excluded — the subsets cover U+0020, but callers trim anyway and a
 * space is never the interesting answer.
 */
export function uncoveredCharacters(face: SignatureFace, text: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const ch of text) {
    if (ch.trim() === '') continue;
    const cp = ch.codePointAt(0);
    if (cp === undefined || faceCovers(face, cp)) continue;
    if (seen.has(ch)) continue;
    seen.add(ch);
    out.push(ch);
  }
  return out;
}

export function coversText(face: SignatureFace, text: string): boolean {
  return uncoveredCharacters(face, text).length === 0;
}
