// The colour a payee's bank card is printed in.
//
// Accounting → People → View → Banking renders a person's payout record as a card
// in their own bank's colours, so the bank is recognised before anything is read.
// A tint is a claim about an institution exactly as a logo is, so it follows the
// same rule `payment-catalog-current-banks.md` §7 sets for the artwork:
//
//   **Every colour below is MEASURED off the shipped logo, never recalled.**
//
// `scripts/derive-bank-brand-colors.mts` prints this table from `public/banks/*.png`
// using `dominantInkColor`, and `bank-card-palette.test.ts` re-derives it from those
// same files on every run. A table that drifts from the artwork fails there rather
// than shipping one bank's card in another bank's colour. To add a bank: ship its
// logo, run the script, paste the line.
//
// A bank with no shipped logo (MariBank, Metrobank, Security Bank and SeaBank
// deliberately have none) and a spelling nobody has claimed both get the NEUTRAL
// card. Guessing a colour for them is the same invented equivalence §10.1 forbids,
// just quieter.
//
// CLIENT-SAFE: pure colour maths, no imports.

/**
 * Measured dominant ink, keyed by official bank key.
 * Generated by `scripts/derive-bank-brand-colors.mts` — do not hand-edit.
 */
export const BANK_BRAND_HEX: Readonly<Record<string, string>> = {
  aub: '#e41b23',
  bank_of_commerce: '#29408e',
  bdo: '#0b2972',
  bpi: '#b11116',
  bpi_banko: '#fdb415',
  cebuana: '#002a44',
  chinabank: '#ed1a37',
  cimb: '#790008',
  davivienda: '#e40619',
  eastwest: '#b5006c',
  fairwinds: '#002f6f',
  gcash: '#002cb8',
  gotyme: '#2d2d3a',
  landbank: '#74bc44',
  maya: '#75eea5',
  maybank: '#ffcf01',
  pnb: '#10357f',
  psbank: '#0855a5',
  rcbc: '#4892cf',
  south_state: '#002d72',
  truist: '#2d1a47',
  unionbank: '#ff8000',
  wise: '#163300',
};

/** The card every bank without a measured colour is printed on. Deliberately a
 *  neutral slate and not a "sort of blue": it must not read as a bank's colour. */
const NEUTRAL_BRAND = '#3f4654';

/**
 * White body text must clear this on the card face. Well above AA's 4.5:1, because
 * the secondary lines are tinted DOWN from white (labels sit at a ~42% mix), and
 * those still have to clear 4.5:1 themselves once they are.
 */
export const CARD_TEXT_CONTRAST_FLOOR = 8.5;

/** Saturation band for the card face. The floor keeps a near-grey brand (GoTyme's
 *  near-black wordmark) from printing as flat charcoal; the ceiling keeps a vivid
 *  one (UnionBank orange, Maya mint) from printing as a toy. */
const SAT_MIN = 14;
const SAT_MAX = 68;

// ── Colour maths ─────────────────────────────────────────────────────────────

interface Rgb { r: number; g: number; b: number }
interface Hsl { h: number; s: number; l: number }

function hexToRgb(hex: string): Rgb {
  const h = hex.replace('#', '');
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }: Rgb): string {
  const c = (n: number) => Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, '0');
  return `#${c(r)}${c(g)}${c(b)}`;
}

function rgbToHsl({ r, g, b }: Rgb): Hsl {
  const rn = r / 255, gn = g / 255, bn = b / 255;
  const max = Math.max(rn, gn, bn), min = Math.min(rn, gn, bn);
  const l = (max + min) / 2;
  const d = max - min;
  if (d === 0) return { h: 0, s: 0, l: l * 100 };
  const s = d / (1 - Math.abs(2 * l - 1));
  let h: number;
  if (max === rn) h = ((gn - bn) / d) % 6;
  else if (max === gn) h = (bn - rn) / d + 2;
  else h = (rn - gn) / d + 4;
  h *= 60;
  if (h < 0) h += 360;
  return { h, s: s * 100, l: l * 100 };
}

function hslToRgb({ h, s, l }: Hsl): Rgb {
  const sn = s / 100, ln = l / 100;
  const c = (1 - Math.abs(2 * ln - 1)) * sn;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = ln - c / 2;
  const [r1, g1, b1] =
    h < 60 ? [c, x, 0] :
    h < 120 ? [x, c, 0] :
    h < 180 ? [0, c, x] :
    h < 240 ? [0, x, c] :
    h < 300 ? [x, 0, c] : [c, 0, x];
  return { r: (r1 + m) * 255, g: (g1 + m) * 255, b: (b1 + m) * 255 };
}

/** WCAG relative luminance. */
function luminance({ r, g, b }: Rgb): number {
  const ch = (v: number) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b);
}

/** WCAG contrast ratio between two hex colours. Exported for the tests that pin
 *  every card face as readable — the check is the point, not an afterthought. */
export function contrastRatio(hexA: string, hexB: string): number {
  const a = luminance(hexToRgb(hexA));
  const b = luminance(hexToRgb(hexB));
  const [hi, lo] = a > b ? [a, b] : [b, a];
  return (hi + 0.05) / (lo + 0.05);
}

/** Mix two hex colours: `amount` of `hexB` into `hexA`. */
function mix(hexA: string, hexB: string, amount: number): string {
  const a = hexToRgb(hexA), b = hexToRgb(hexB);
  return rgbToHex({
    r: a.r + (b.r - a.r) * amount,
    g: a.g + (b.g - a.g) * amount,
    b: a.b + (b.b - a.b) * amount,
  });
}

// ── The card face ────────────────────────────────────────────────────────────

export interface BankCardPalette {
  /** Brand ink exactly as measured — shown only where contrast rules do not apply
   *  (the hairline edge and the chip), never behind text. */
  accent: string;
  /** Card face, top stop. White text on this clears CARD_TEXT_CONTRAST_FLOOR. */
  surface: string;
  /** Card face, bottom stop — the same hue, deeper, so the face reads as raking
   *  light across an object rather than as a flat fill. */
  surfaceDeep: string;
  /** True when this is a measured brand colour rather than the neutral fallback. */
  branded: boolean;
}

/**
 * Darken toward the hue's own black until white text clears the floor.
 *
 * Lightness only — the hue is never rotated, and the saturation band is applied
 * first, so Maybank's card stays gold and UnionBank's stays orange. A yellow brand
 * cannot host white text at its own lightness (`#ffcf01` gives white 1.2:1), and the
 * alternative — dark ink on the light cards, white on the rest — would make one card
 * in the set look like a different component.
 */
function faceFor(brandHex: string): { surface: string; surfaceDeep: string } {
  const hsl = rgbToHsl(hexToRgb(brandHex));
  const s = Math.max(SAT_MIN, Math.min(SAT_MAX, hsl.s));
  for (let l = Math.min(hsl.l, 34); l >= 4; l -= 0.5) {
    const surface = rgbToHex(hslToRgb({ h: hsl.h, s, l }));
    if (contrastRatio(surface, '#ffffff') >= CARD_TEXT_CONTRAST_FLOOR) {
      return {
        surface,
        // Toward the same hue's black, never toward neutral grey, so the gradient
        // stays one material instead of fading out.
        surfaceDeep: rgbToHex(hslToRgb({ h: hsl.h, s, l: Math.max(3, l - 9) })),
      };
    }
  }
  // Unreachable for any real colour — L=4 is near-black — but a loop that can fall
  // through says what it returns rather than leaving that to the caller.
  return { surface: '#111318', surfaceDeep: '#08090c' };
}

/**
 * The card face for an official bank key.
 *
 * A null key, or a key with no measured colour, returns the NEUTRAL card with
 * `branded: false`. That is a normal outcome — the caller draws the same card
 * geometry, with no brand claim on it.
 */
export function bankCardPalette(key: string | null | undefined): BankCardPalette {
  const brand = key ? BANK_BRAND_HEX[key] : undefined;
  const face = faceFor(brand ?? NEUTRAL_BRAND);
  return {
    accent: brand ?? NEUTRAL_BRAND,
    surface: face.surface,
    surfaceDeep: face.surfaceDeep,
    branded: Boolean(brand),
  };
}

/**
 * The strongest mix toward the surface that still clears `minRatio` against it.
 *
 * Written as a search rather than a constant because a constant is only ever right
 * for the colours that existed when it was picked: a flat 42% mix reads beautifully
 * on BDO's navy and falls to 3.84:1 on AUB's red, and the next logo anyone adds gets
 * a different answer again. Backing off toward white until the ratio is met makes the
 * guarantee structural — every card is as muted as it can afford to be, and none is
 * more muted than that.
 */
function mixedInk(surface: string, desired: number, minRatio: number): string {
  for (let amount = desired; amount > 0; amount -= 0.02) {
    const candidate = mix('#ffffff', surface, amount);
    if (contrastRatio(surface, candidate) >= minRatio) return candidate;
  }
  return '#ffffff';
}

/**
 * Ink for a card face. Secondary text is mixed DOWN from white toward the card's own
 * surface rather than set to a grey, so the labels belong to the card's material
 * instead of sitting on top of it — the craft rule that secondary text on a coloured
 * surface is tinted from that surface, never greyed.
 *
 * Both tinted levels clear AA against the face they sit on, by construction.
 */
export function bankCardInk(palette: BankCardPalette): {
  primary: string;
  secondary: string;
  label: string;
} {
  return {
    primary: '#ffffff',
    // Account holder, bank name, the rail chip — data, so held well above AA.
    secondary: mixedInk(palette.surface, 0.28, 6),
    // Field captions. Quietest ink on the card, and still AA on its own face.
    label: mixedInk(palette.surface, 0.42, 4.5),
  };
}
