-- Reconcile: update global_master_list Work Email to the seeded rates' Work Email,
-- matching by Name (normalized: lowercase + alphanum only) within Hogan Smith Law dept.
-- This realigns the join key so rates rows and master rows share a Work Email going forward.

WITH sheet(work_email, name, name_key) AS (
  VALUES
    ('acea@simple.biz', 'Arrieta, Ace "Ace"', 'arrietaaceace'),
    ('airahe@simple.biz', 'Estologa, Airah Sol D.  "Airah"', 'estologaairahsoldairah'),
    ('aja@simple.biz', 'Amorado, Joralyn "AJ"', 'amoradojoralynaj'),
    ('alainp@simple.biz', 'Peque, John Alain Ezron M. "Alain"', 'pequejohnalainezronmalain'),
    ('alb@simple.biz', 'Butantan, Albern "Al"', 'butantanalbernal'),
    ('alenm@simple.biz', 'Mendoza  Xerxis Alen "Alen"', 'mendozaxerxisalenalen'),
    ('alexb@simple.biz', 'Busano, Lorenzo "Alex"', 'busanolorenzoalex'),
    ('alexb@simplesitecompany.com', 'Busano, Lorenzo "Alex"', 'busanolorenzoalex'),
    ('alexe@simple.biz', 'Evangelista, Alexander "Alex"', 'evangelistaalexanderalex'),
    ('alexr@simple.biz', 'De Rama, Rufio Alexander "Alex"', 'deramarufioalexanderalex'),
    ('algiem@simple.biz', 'Manzano, Algie Anne R "Algie"', 'manzanoalgieanneralgie'),
    ('amiea@simple.biz', 'Arbol, Amelou "Amie"', 'arbolamelouamie'),
    ('andret@simple.biz', 'Tolentino, Romel T. "Andre"', 'tolentinoromeltandre'),
    ('andrewg@simple.biz', 'Gersaniba, Andrew "Andrew"', 'gersanibaandrewandrew'),
    ('andrewg@simplesitecompany.com', 'Gersaniba, Andrew "Andrew"', 'gersanibaandrewandrew'),
    ('andrewma@simple.biz', 'Manteza, Andrew "Andrew"', 'mantezaandrewandrew'),
    ('andym@simple.biz', 'Manzano, Andy "Andy"', 'manzanoandyandy'),
    ('andym@simplesitecompany.com', 'Manzano, Andy "Andy"', 'manzanoandyandy'),
    ('angelc@simple.biz', 'Cosep, Angel Mae "Angel"', 'cosepangelmaeangel'),
    ('angeld@simple.biz', 'Dalusong, Angelica "Angel"', 'dalusongangelicaangel'),
    ('angelicai@simple.biz', 'Igbalic, Angelica', 'igbalicangelica'),
    ('annel@simple.biz', 'La Victoria, Jichelle "Anne"', 'lavictoriajichelleanne'),
    ('anng@simple.biz', 'Gevido, Annrose "Ann"', 'gevidoannroseann'),
    ('applee@simple.biz', 'Esguerra, Apple Kaye "Kaye"', 'esguerraapplekayekaye'),
    ('applef@simple.biz', 'Fajardo, Apple Gay A "Apple"', 'fajardoapplegayaapple'),
    ('aprilc@simple.biz', 'Carriaga, April Mae "April"', 'carriagaaprilmaeapril'),
    ('aprill@simple.biz', 'Lapaz, April "April"', 'lapazaprilapril'),
    ('ara@simple.biz', 'Breboneria, Ara "Ara"', 'breboneriaaraara'),
    ('arcd@simple.biz', 'Dordas, Arcturus "Arc"', 'dordasarcturusarc'),
    ('aremb@simple.biz', 'Badajos, Arem "Arem"', 'badajosaremarem'),
    ('arr@simple.biz', 'Rosales, Anna Rowella "AR"', 'rosalesannarowellaar'),
    ('artp@simple.biz', 'Plaza, Art Jr.  "Art"', 'plazaartjrart'),
    ('arvsn@simple.biz', 'Navarro, Arvin "Arvs"', 'navarroarvinarvs'),
    ('ashleyb@simple.biz', 'Baragona, Aslamah "Ashley"', 'baragonaaslamahashley'),
    ('aubreyt@simple.biz', 'Tulaña, Aubrey Joy "Aubrey"', 'tulaaaubreyjoyaubrey'),
    ('aurai@simple.biz', 'Ibañez, Auraluz A. "Aura"', 'ibaezauraluzaaura'),
    ('beao@simple.biz', 'Olarte, Bea Patricia  "Bea"', 'olartebeapatriciabea'),
    ('beckyp@simple.biz', 'Pascual, Rebecca "Becky"', 'pascualrebeccabecky'),
    ('bela@simple.biz', 'Anastacio, Lovella "Belle"', 'anastaciolovellabelle'),
    ('benc@simple.biz', 'Cahoy, Albenjie "Ben"', 'cahoyalbenjieben'),
    ('brandong@simple.biz', 'Gonzales, Brandon Jay "Brandon"', 'gonzalesbrandonjaybrandon'),
    ('breen@simple.biz', 'Nalangan, Aubrey Therese "Bree"', 'nalanganaubreytheresebree'),
    ('brianr@simple.biz', 'Rieta, Brian Joshua  "Brian"', 'rietabrianjoshuabrian'),
    ('brixf@simple.biz', 'Flores, Brix Cougar "Brix"', 'floresbrixcougarbrix'),
    ('camillm@simple.biz', 'Mercado, Joyce Camill "Camill"', 'mercadojoycecamillcamill'),
    ('cannys@simple.biz', 'Savillo, Canny Rose  "Canny"', 'savillocannyrosecanny'),
    ('carlb@simple.biz', 'Bernardo, Carl Phillip "Carl"', 'bernardocarlphillipcarl'),
    ('carlo@simple.biz', 'Cabrera, Justine Carl "Carl"', 'cabrerajustinecarlcarl'),
    ('carlylec@simple.biz', 'Cortes, Carlyle "Carlyle"', 'cortescarlylecarlyle'),
    ('cathd@simple.biz', 'Dublin, Catherine "Cath"', 'dublincatherinecath'),
    ('cathl@simple.biz', 'Llanes, Cathyrine "Cath"', 'llanescathyrinecath'),
    ('cathys@simple.biz', 'Siochi, Catherine Rina "Cathy"', 'siochicatherinerinacathy'),
    ('cessp@simple.biz', 'Perez, Princess Joan "Cess"', 'perezprincessjoancess'),
    ('charlesc@simple.biz', 'Dela Cruz, Charles Kerzey "Charles"', 'delacruzcharleskerzeycharles'),
    ('charmd@simple.biz', 'Deleverio, Charmaine "Charm"', 'deleveriocharmainecharm'),
    ('chaseg@simple.biz', 'Chase Gerundiano  "Chase"', 'chasegerundianochase'),
    ('chaseg@simplesitecompany.com', 'Chase Gerundiano  "Chase"', 'chasegerundianochase'),
    ('chelzyc@simple.biz', 'Chavez, Chelzy "Chelzy"', 'chavezchelzychelzy'),
    ('chet@simple.biz', 'Tecson, Ma. Theresa "Che"', 'tecsonmatheresache'),
    ('choloh@simple.biz', 'Hernandez, Cholo "Cholo"', 'hernandezcholocholo'),
    ('chrise@simple.biz', 'Enriquez, Chris Chan "Chris"', 'enriquezchrischanchris'),
    ('chrism@simple.biz', 'Mamhot, Niño Christian A. "Chris"', 'mamhotniochristianachris'),
    ('christiannr@simple.biz', 'Roa, Christian "Chris"', 'roachristianchris'),
    ('cindyg@simple.biz', 'Gonzales, Cindy "Cindy"', 'gonzalescindycindy'),
    ('cjc@simple.biz', 'Cortes, Cee Jei "CJ"', 'cortesceejeicj'),
    ('clarizr@simple.biz', 'Rosales, Clariza Mae  "Clariz"', 'rosalesclarizamaeclariz'),
    ('claudep@simple.biz', 'Punay, Claudine A "Claude"', 'punayclaudineaclaude'),
    ('cliffl@simple.biz', 'Lopez, Cliff Roven "Cliff''', 'lopezcliffrovencliff'),
    ('cliffl@simplesitecompany.com', 'Lopez, Cliff Roven "Cliff''', 'lopezcliffrovencliff'),
    ('clydem@simple.biz', 'Mangawang, Clyde "Clyde"', 'mangawangclydeclyde'),
    ('crisc@simple.biz', 'Cañete, Ma. Cris Mae "Cris"', 'caetemacrismaecris'),
    ('dales@simple.biz', 'Delos Santos, Dale "Dale"', 'delossantosdaledale'),
    ('dana@simple.biz', 'Abad, Danilo Jr "Dan"', 'abaddanilojrdan'),
    ('dancp@simple.biz', 'Pagharion, Dan Carlo "Dan"', 'paghariondancarlodan'),
    ('danm@simple.biz', 'Masacote, Dan Kristoffer "Dan"', 'masacotedankristofferdan'),
    ('daver@simple.biz', 'Retis, John David  "Dave"', 'retisjohndaviddave'),
    ('dextert@simple.biz', 'Tagulinao, Ryan Dexter "Dexter"', 'tagulinaoryandexterdexter'),
    ('donb@simple.biz', 'Billones, Brandon "Don"', 'billonesbrandondon'),
    ('dond@simple.biz', 'Danosos, Doness Taboada "Don"', 'danososdonesstaboadadon'),
    ('ede@simple.biz', 'Espiritu, Edric "Ed"', 'espirituedriced'),
    ('edi@simple.biz', 'Infante, Eddie "ED"', 'infanteeddieed'),
    ('edm@simple.biz', 'Mabaga, Edrown John "ED"', 'mabagaedrownjohned'),
    ('edryckm@simple.biz', 'Mira, Edryck Mae N "Ed"', 'miraedryckmaened'),
    ('edzg@simple.biz', 'Garcia, Edlaine "Edz"', 'garciaedlaineedz'),
    ('ejm@simple.biz', 'Melchor, Ej "EJ"', 'melchorejej'),
    ('elaizaha@simple.biz', 'Alcanzo, Elaizah Jean " Elaizah"', 'alcanzoelaizahjeanelaizah'),
    ('elaz@simple.biz', 'Zaspa, Dionela Rose "Nela"', 'zaspadionelarosenela'),
    ('elmob@simple.biz', 'Biol, Elmer "Elmo"', 'biolelmerelmo'),
    ('emill@simple.biz', 'De Leon, Emiliano "Emil"', 'deleonemilianoemil'),
    ('emmanuelf@simple.biz', 'Frivaldo, Emmanuel John "Emmanuel"', 'frivaldoemmanueljohnemmanuel'),
    ('emss@simple.biz', 'Solon, Emily "Ems"', 'solonemilyems'),
    ('erict@simple.biz', 'Teano, Ericson "Eric"', 'teanoericsoneric'),
    ('erjiee@simple.biz', 'Estolonio, Erjie "Erjie"', 'estolonioerjieerjie'),
    ('eulap@simple.biz', 'Pacheco, Eula Jane J.', 'pachecoeulajanej'),
    ('ferdieb@simple.biz', 'Bondoc, Ferdinand "Ferdie"', 'bondocferdinandferdie'),
    ('field@simple.biz', 'Deguito, Fiel "Fiel"', 'deguitofielfiel'),
    ('francem@simple.biz', 'Magallon, Francis "France"', 'magallonfrancisfrance'),
    ('francisf@simple.biz', 'Boybanting, Francis Jay "Francis"', 'boybantingfrancisjayfrancis'),
    ('franzs@simple.biz', 'Sancio, Franz Vincent  "Franz"', 'sanciofranzvincentfranz'),
    ('fredi@simple.biz', 'Sevilla III, Seigfredo "Fred"', 'sevillaiiiseigfredofred'),
    ('geloa@simple.biz', 'Abuel, Paul Angelo R "Gelo"', 'abuelpaulangelorgelo'),
    ('gelp@simple.biz', 'Paltao, Gellie Rose "Gel"', 'paltaogellierosegel'),
    ('gelp@simplesitecompany.com', 'Paltao, Gellie Rose "Gel"', 'paltaogellierosegel'),
    ('genep@simple.biz', 'Pasay, Gene Alphonse "Gene"', 'pasaygenealphonsegene'),
    ('gleng@simple.biz', 'Go, Glenda "Glen"', 'goglendaglen'),
    ('grahama@simple.biz', 'Alolod, Graham Christopher P. "Graham"', 'alolodgrahamchristopherpgraham'),
    ('guiaq@simple.biz', 'Quillosa, Guia Maria Mercado "Guia"', 'quillosaguiamariamercadoguia'),
    ('guiaq@simplesitecompany.com', 'Quillosa, Guia Maria Mercado "Guia"', 'quillosaguiamariamercadoguia'),
    ('gyd@simple.biz', 'Tura, Gyd', 'turagyd'),
    ('hannaa@simple.biz', 'Abad, Hannah Lynn "Hannah"', 'abadhannahlynnhannah'),
    ('hannan@simple.biz', 'Nacional, Hanna Mae "Hanna"', 'nacionalhannamaehanna'),
    ('hannesm@simple.biz', 'Mendez, Hannes "Hannes"', 'mendezhanneshannes'),
    ('hendryp@simple.biz', 'Pamatian, Hendry "Hendry"', 'pamatianhendryhendry'),
    ('inchetm@simple.biz', 'Marasigan, Ma. Victoria "Inchet"', 'marasiganmavictoriainchet'),
    ('ireneh@simple.biz', 'Hernandez, Ma. Irene Ruth "Irene"', 'hernandezmaireneruthirene'),
    ('irisb@simple.biz', 'Borgonia, Iris M.', 'borgoniairism'),
    ('isaact@simple.biz', 'Tesalona, Isaac John "Isaac"', 'tesalonaisaacjohnisaac'),
    ('ivy@simple.biz', 'Antig, Ivy Marie', 'antigivymarie'),
    ('ivym@simple.biz', 'Antig, Ivy Marie', 'antigivymarie'),
    ('jakej@simple.biz', 'Jackson, Jacob John "Jake"', 'jacksonjacobjohnjake'),
    ('jaket@simple.biz', 'Tapere, John Benedict "Jake"', 'taperejohnbenedictjake'),
    ('jamg@simple.biz', 'Guanzon, Jamaica P. "Jam"', 'guanzonjamaicapjam'),
    ('jammers@simple.biz', 'Solijon, Jammer  "Jam"', 'solijonjammerjam'),
    ('janinec@simple.biz', 'Certeza, Janine M "Janine"', 'certezajaninemjanine'),
    ('jannj@simple.biz', 'Jumonong, Jann Andrei "Jann"', 'jumonongjannandreijann'),
    ('janp@simple.biz', 'Del Prado, V-Jan  "Jan"', 'delpradovjanjan'),
    ('jaya@simple.biz', 'Aguado, Jayson "Jay"', 'aguadojaysonjay'),
    ('jaya@simplesitecompany.com', 'Aguado, Jayson "Jay"', 'aguadojaysonjay'),
    ('jayh@simple.biz', 'Hernandez, John Michael', 'hernandezjohnmichael'),
    ('jaysond@simple.biz', 'Dao-ayan, Jayson O.  "Jayson"', 'daoayanjaysonojayson'),
    ('jayveea@simple.biz', 'Aliser, Jayvee Lloyd "Jayvee"', 'aliserjayveelloydjayvee'),
    ('jaywlc@simple.biz', 'Cabatingan, Mark Jaywl "Mark"', 'cabatinganmarkjaywlmark'),
    ('jazminer@simple.biz', 'Roa, Sajda "Jazmine"', 'roasajdajazmine'),
    ('jazzr@simple.biz', 'Redulla, Jazz Javier', 'redullajazzjavier'),
    ('jcp@simple.biz', 'Pascual, John Christopher "JC"', 'pascualjohnchristopherjc'),
    ('jdd@simple.biz', 'Dagatan, Jensen "JD"', 'dagatanjensenjd'),
    ('jeant@simple.biz', 'Tupas, Honey Jean "Jean"', 'tupashoneyjeanjean'),
    ('jebr@simple.biz', 'Ravanilla, Jeb Patrick  "Jeb"', 'ravanillajebpatrickjeb'),
    ('jedp@simple.biz', 'Porquez Jeremy Jed "Jed"', 'porquezjeremyjedjed'),
    ('jehdb@simple.biz', 'Basman,Jehd Monsour "Jhed"', 'basmanjehdmonsourjhed'),
    ('jemt@simple.biz', 'Tañajora, Jeremy "Jem"', 'taajorajeremyjem'),
    ('jemv@simple.biz', 'Vasquez, Jeremy "Jem"', 'vasquezjeremyjem'),
    ('jenessap@simple.biz', 'Paraiso, Janessa "Jen"', 'paraisojanessajen'),
    ('jeni@simple.biz', 'Ipili, Lynie Jane "Jen"', 'ipililyniejanejen'),
    ('jenl@simple.biz', 'Lagos, Jennifer "Jen"', 'lagosjenniferjen'),
    ('jeoa@simple.biz', 'Agbo, Jeofry Kim "Jeo"', 'agbojeofrykimjeo'),
    ('jeriemym@simple.biz', 'Adove, Jeriemy Mckinly "Jeriemy"', 'adovejeriemymckinlyjeriemy'),
    ('jeromea@simple.biz', 'Aguirre, Jerome G "Jerome"', 'aguirrejeromegjerome'),
    ('jerrekl@simple.biz', 'Lim, Jerrek Anthony', 'limjerrekanthony'),
    ('jerryl@simple.biz', 'Langcuyan, Jerelee "Jerry"', 'langcuyanjereleejerry'),
    ('jetg@simple.biz', 'Galino, Jet "Jet"', 'galinojetjet'),
    ('jigsj@simple.biz', 'Jugan, Randy John "Jigs"', 'juganrandyjohnjigs'),
    ('jimb@simple.biz', 'Boongaling, Gim Clark "Jim"', 'boongalinggimclarkjim'),
    ('jms@simple.biz', 'Sarana, John Michael R "JM"', 'saranajohnmichaelrjm'),
    ('johannas@simple.biz', 'Sacedon, Johanna Grace "Johanna"', 'sacedonjohannagracejohanna'),
    ('johannas@simplesitecompany.com', 'Sacedon, Johanna Grace "Johanna"', 'sacedonjohannagracejohanna'),
    ('johnbv@simple.biz', 'Villanueva, John B "John"', 'villanuevajohnbjohn'),
    ('johnl@simple.biz', 'Lagos, John Michael "John"', 'lagosjohnmichaeljohn'),
    ('johnq@simple.biz', 'Querijero, John Rhiel "John"', 'querijerojohnrhieljohn'),
    ('johnwp@simple.biz', 'Paule, John Westley "Westley"', 'paulejohnwestleywestley'),
    ('joloe@simple.biz', 'Esguerra, Jolo Miguel "Jolo"', 'esguerrajolomigueljolo'),
    ('jomsa@simple.biz', 'Arce, Jomar "Jom"', 'arcejomarjom'),
    ('jonj@simple.biz', 'Jaring, Jon Francis "Jon"', 'jaringjonfrancisjon'),
    ('josephf@simple.biz', 'Florita, Joseph Anthony "Joseph"', 'floritajosephanthonyjoseph'),
    ('josephinet@simple.biz', 'Torralba, Josephine', 'torralbajosephine'),
    ('josephr@simple.biz', 'Robles, Joseph "Joseph"', 'roblesjosephjoseph'),
    ('josha@simple.biz', 'Aquino, Joshua Jake "Josh"', 'aquinojoshuajakejosh'),
    ('josied@simple.biz', 'Doon, Josephine "Josie"', 'doonjosephinejosie'),
    ('joy@hogansmith.com', 'Baldonebro, Joycel "Joy"', 'baldonebrojoyceljoy'),
    ('joyb@simple.biz', 'Baldonebro, Joycel "Joy"', 'baldonebrojoyceljoy'),
    ('jpb@simple.biz', 'Bacallan , John Paul "JP"', 'bacallanjohnpauljp'),
    ('judyannc@simple.biz', 'Canales,Judy Ann  "Judy"', 'canalesjudyannjudy'),
    ('judyannc@simplesitecompany.com', 'Canales,Judy Ann  "Judy"', 'canalesjudyannjudy'),
    ('juliane@simple.biz', 'Elevazo, Julian "Julian"', 'elevazojulianjulian'),
    ('juliec@simple.biz', 'Credo, Julie Ann "Julie"', 'credojulieannjulie'),
    ('justineb@simple.biz', 'Buenvenida, Bong Justine "Justine"', 'buenvenidabongjustinejustine'),
    ('kailab@simple.biz', 'Benito, Mechaila "Kaila"', 'benitomechailakaila'),
    ('karln@simple.biz', 'Noynay, Karl Louie "Karl"', 'noynaykarllouiekarl'),
    ('karmina@simple.biz', 'Dulu, Maria Karmina "Mina"', 'dulumariakarminamina'),
    ('kated@simple.biz', 'Danao, Catline Rose "Kate"', 'danaocatlinerosekate'),
    ('katet@simple.biz', 'Tugna, Rencel Khate "Kate"', 'tugnarencelkhatekate'),
    ('kathl@simple.biz', 'Lapure, Kathleen "Kath"', 'lapurekathleenkath'),
    ('kathl@simplesitecompany.com', 'Lapure, Kathleen "Kath"', 'lapurekathleenkath'),
    ('kayea@simple.biz', 'Agustin, Kaye Lanie Munoz', 'agustinkayelaniemunoz'),
    ('keithc@simple.biz', 'Cayosa, Keith Xavier Jonathan"Keith"', 'cayosakeithxavierjonathankeith'),
    ('kellyc@simple.biz', 'Canave, Melisa Kelly "Kelly"', 'canavemelisakellykelly'),
    ('kennm@simple.biz', 'Melliza, Kenneth "Ken"', 'mellizakennethken'),
    ('kevinu@simple.biz', 'Uy, Kevin Karl "Kevin"', 'uykevinkarlkevin'),
    ('khrism@simple.biz', 'Moises, Khrisna "Khris"', 'moiseskhrisnakhris'),
    ('kimbr@simple.biz', 'Briones, Kim "Kim"', 'brioneskimkim'),
    ('kimr@simple.biz', 'Roxas, Kim Augusteine "Kim"', 'roxaskimaugusteinekim'),
    ('kristinec@simple.biz', 'Labo, Kristine Abigail "Kristine"', 'labokristineabigailkristine'),
    ('kryzeln@simple.biz', 'Navarosa, Kryzel "Kryzel"', 'navarosakryzelkryzel'),
    ('ktelc@simple.biz', 'Catuday, Kristel Joy "Ktel"', 'catudaykristeljoyktel'),
    ('kyrag@simple.biz', 'Galicia, Kyra Archie " Kyra"', 'galiciakyraarchiekyra'),
    ('lanf@simple.biz', 'Fuertes, Lani', 'fuerteslani'),
    ('lauricej@simple.biz', 'Justiniane, Laurice Monette C "Laurice"', 'justinianelauricemonetteclaurice'),
    ('lawrenced@simple.biz', 'David, Lawrence Francis "Lawrence"', 'davidlawrencefrancislawrence'),
    ('leighl@simple.biz', 'Lawa, Leigh "Leigh"', 'lawaleighleigh'),
    ('liccac@simple.biz', 'Castillo, Noreen Licca "Licca"', 'castillonoreenliccalicca'),
    ('liefe@simple.biz', 'Enriquez, Lief Lester "Leif"', 'enriquezlieflesterleif'),
    ('lincolnm@simple.biz', 'Moguies, Lincoln Eman', 'moguieslincolneman'),
    ('linkm@simple.biz', 'Mamaril, Lincoln Gerard A "Link"', 'mamarillincolngerardalink'),
    ('lorar@simple.biz', 'Roflo, Elora Dawn Del Mundo "Lora"', 'rofloeloradawndelmundolora'),
    ('loriem@simple.biz', 'San Mateo, Lorie Ann "Lorie"', 'sanmateolorieannlorie'),
    ('lovelyc@simple.biz', 'Celis, Lovely V "Love"', 'celislovelyvlove'),
    ('luisd@simple.biz', 'Damasco, Luis "Luis"', 'damascoluisluis'),
    ('luisd@simplesitecompany.com', 'Damasco, Luis "Luis"', 'damascoluisluis'),
    ('lynj@simple.biz', 'Johnson, Shielalyn "Lyn"', 'johnsonshielalynlyn'),
    ('lynnb@simple.biz', 'Binas, Petalyn "Lynn"', 'binaspetalynlynn'),
    ('mackp@simple.biz', 'Joseph Michael Plugio "Mack"', 'josephmichaelplugiomack'),
    ('mackyj@simple.biz', 'Jordan, Reymark Japon "Macky"', 'jordanreymarkjaponmacky'),
    ('macp@simple.biz', 'Pahunang Mark Anthony L. "Mac"-', 'pahunangmarkanthonylmac'),
    ('maddies@simple.biz', 'Sabado, Madison Lori L "Maddie"', 'sabadomadisonlorilmaddie'),
    ('marbieb@simple.biz', 'Buat, Janmarie Bernadette Ocampo "Marbie"', 'buatjanmariebernadetteocampomarbie'),
    ('marcusu@simple.biz', 'Umpad, Marcus "Marcus"', 'umpadmarcusmarcus'),
    ('mariam@simple.biz', 'Magallano, Maria Corazon "Maria"', 'magallanomariacorazonmaria'),
    ('maricard@simple.biz', 'Docallos, Maricar "Maricar"', 'docallosmaricarmaricar'),
    ('maricorc@simple.biz', 'Cruz, Maricor Lorenzo "Marie"', 'cruzmaricorlorenzomarie'),
    ('marie@simple.biz', 'Calugay, Catherine Marie "Marie"', 'calugaycatherinemariemarie'),
    ('mariea@simple.biz', 'Fulleros, Marie Antonette "Marie"', 'fullerosmarieantonettemarie'),
    ('mariec@simple.biz', 'Calugay, Catherine Marie "Marie"', 'calugaycatherinemariemarie'),
    ('mariely@simple.biz', 'Yungco, Marielace Buena Fe "Mariel"', 'yungcomarielacebuenafemariel'),
    ('mariettac@simple.biz', 'Candor, Marietta "May"', 'candormariettamay'),
    ('marjf@simple.biz', 'Fernandez, Marjorie "Marj"', 'fernandezmarjoriemarj'),
    ('marjunm@simple.biz', 'Macamay, Marjun "Marjun"', 'macamaymarjunmarjun'),
    ('markd@simple.biz', 'Descalzo, Mark Vincent "Mark"', 'descalzomarkvincentmark'),
    ('markmo@simple.biz', 'Molarte, Mark', 'molartemark'),
    ('mats@simple.biz', 'Salas, Mathew King "Mat"', 'salasmathewkingmat'),
    ('mayi@simple.biz', 'Inggo, Maybelle "May"', 'inggomaybellemay'),
    ('mayt@simple.biz', 'Tampos, Mae "May"', 'tamposmaemay'),
    ('melchezedeks@simple.biz', 'Sumandang, Melchezedek "Mel"', 'sumandangmelchezedekmel'),
    ('melm@simple.biz', 'Manalo, Armel D. "Mel"', 'manaloarmeldmel'),
    ('melvsf@simple.biz', 'Faeldan, Melvin "Melvs"', 'faeldanmelvinmelvs'),
    ('mgm@simple.biz', 'Manalo, Mary Grace "MG"', 'manalomarygracemg'),
    ('miahl@simple.biz', 'Leosala , Nehemiah "Miah"', 'leosalanehemiahmiah'),
    ('miaj@simple.biz', 'Benedictos, Miarela Javier "Mia"', 'benedictosmiarelajaviermia'),
    ('michaelb@simple.biz', 'Bacalla, Michael Ryan "Mike"', 'bacallamichaelryanmike'),
    ('mickyr@simple.biz', 'Reynante, Micky Jenelyn A "Micky"', 'reynantemickyjenelynamicky'),
    ('migsl@simple.biz', 'Locmayon, Miguel "Migs"', 'locmayonmiguelmigs'),
    ('migsl@simplesitecompany.com', 'Locmayon, Miguel "Migs"', 'locmayonmiguelmigs'),
    ('mikeb@simple.biz', 'Baillo, Jan Michael M "Mike"', 'baillojanmichaelmmike'),
    ('mikekja@simple.biz', 'Agtag, Mike King Jay Erano "Mike"', 'agtagmikekingjayeranomike'),
    ('mikep@simple.biz', 'Placia, Michael S "Mike"', 'placiamichaelsmike'),
    ('miket@simple.biz', 'Torres, Michael John "Mike"', 'torresmichaeljohnmike'),
    ('mina@simple.biz', 'Dulu, Maria Karmina "Mina"', 'dulumariakarminamina'),
    ('minad@simple.biz', 'Dulu, Maria Karmina "Mina"', 'dulumariakarminamina'),
    ('mitsa@simple.biz', 'Aguilar Mitsume "Mits"', 'aguilarmitsumemits'),
    ('nadinec@simple.biz', 'Chavez, Nadine', 'chaveznadine'),
    ('natel@simple.biz', 'Lunar, Jonathan "Nate"', 'lunarjonathannate'),
    ('neliab@simple.biz', 'Boiser, Nelia "Nelia"', 'boisernelianelia'),
    ('nesm@simple.biz', 'Macajelos, Nessan "Nes"', 'macajelosnessannes'),
    ('nesm@simplesitecompany.com', 'Macajelos, Nessan "Nes"', 'macajelosnessannes'),
    ('nete@simple.biz', 'Ebardo, Carol "Net"', 'ebardocarolnet'),
    ('nics@simple.biz', 'Sornito, Nicole "Nic"', 'sornitonicolenic'),
    ('nikaa@simple.biz', 'Aldohueza Nika Alexis "Nika"', 'aldohuezanikaalexisnika'),
    ('ninac@simple.biz', 'Cruz, Nina Christina "Nina"', 'cruzninachristinanina'),
    ('noelm@simple.biz', 'Manlulu, Noel "Noel"', 'manlulunoelnoel'),
    ('noimeg@simple.biz', 'Gaspar, Noime "Noime"', 'gasparnoimenoime'),
    ('norwinb@simple.biz', 'Binas, Norwin "Norwin"', 'binasnorwinnorwin'),
    ('olie@simple.biz', 'Estanislao, Olimar Ramos "Oli""', 'estanislaoolimarramosoli'),
    ('patv@simple.biz', 'Velasco, Patricia Mikaela "Pat"', 'velascopatriciamikaelapat'),
    ('queenb@simple.biz', 'Baguio, Queencis Eve "Queen"', 'baguioqueencisevequeen'),
    ('rachelc@simple.biz', 'Cagape, Rachel Amor "Rachel"', 'cagaperachelamorrachel'),
    ('rafa@simple.biz', 'Andres, Rafael Angelo "Raf"', 'andresrafaelangeloraf'),
    ('rainp@simple.biz', 'Postrano, Reynan "Rain"', 'postranoreynanrain'),
    ('ralfp@simple.biz', 'Pamintuan, Joseph Ralf "Joe"', 'pamintuanjosephralfjoe'),
    ('ralphr@simple.biz', 'Ramirez, Ralph William "Ralph"', 'ramirezralphwilliamralph'),
    ('raphs@simple.biz', 'Sepnio, Raphael "Raph"', 'sepnioraphaelraph'),
    ('rayc@simple.biz', 'Conejos, Jhon Rhey "Ray"', 'conejosjhonrheyray'),
    ('rayc@simplesitecompany.com', 'Conejos, Jhon Rhey "Ray"', 'conejosjhonrheyray'),
    ('reeds@simple.biz', 'Salvador, Reed Jensen "Reed"', 'salvadorreedjensenreed'),
    ('reinal@simple.biz', 'Lawas, Reina', 'lawasreina'),
    ('renards@simple.biz', 'Seledio, Renard "Renard"', 'selediorenardrenard'),
    ('rend@simple.biz', 'Sto Domingo, Mariren "Ren"', 'stodomingomarirenren'),
    ('richardm@simple.biz', 'Manuyag, Richard Angelo "Richard"', 'manuyagrichardangelorichard'),
    ('robm@simple.biz', 'Mula, Robert "Rob"', 'mularobertrob'),
    ('robm@simplesitecompany.com', 'Mula, Robert "Rob"', 'mularobertrob'),
    ('robp@simple.biz', 'Pegorosa, Bel Robert "Rob"', 'pegorosabelrobertrob'),
    ('robt@simple.biz', 'Tantiado,  Rob "Rob"', 'tantiadorobrob'),
    ('rochelled@simple.biz', 'Dumlao, Rochelle Grace "Rochelle"', 'dumlaorochellegracerochelle'),
    ('rockym@simple.biz', 'Macalinga, Rocky Jedd "Rocky"', 'macalingarockyjeddrocky'),
    ('roda@simple.biz', 'Alejandre, Girod "Rod"', 'alejandregirodrod'),
    ('rosed@simple.biz', 'Dente, Rosemary Joy "Rose"', 'denterosemaryjoyrose'),
    ('rosep@simple.biz', 'Principe, Roses "Rose"', 'principerosesrose'),
    ('roses@simple.biz', 'Sardan, Rosemarie Marquez "Rose"', 'sardanrosemariemarquezrose'),
    ('ruffag@simple.biz', 'Gallego, Ruffa Mae "Ruffa"', 'gallegoruffamaeruffa'),
    ('ruffamaeg@simple.biz', 'Generalao, Ruffa Mae  "Ruffa"', 'generalaoruffamaeruffa'),
    ('russelm@simple.biz', 'Macabali, Russel "Russel"', 'macabalirusselrussel'),
    ('ruswellb@simple.biz', 'Bartolata, Ruswell  ""Ruswell"', 'bartolataruswellruswell'),
    ('rvr@simple.biz', 'Rivera, Roy "RV"', 'riveraroyrv'),
    ('ryej@simple.biz', 'De Jesus, Ryan Rigel "Rye"', 'dejesusryanrigelrye'),
    ('sarahf@simple.biz', 'Fantilagan, Sarah "Sarah "', 'fantilagansarahsarah'),
    ('sarahf@simplesitecompany.com', 'Fantilagan, Sarah "Sarah "', 'fantilagansarahsarah'),
    ('shaie@simple.biz', 'Espiritu, Shaira "Shai"', 'espiritushairashai'),
    ('shairal@simple.biz', 'Laki, Shaira Lyra "Shaira"', 'lakishairalyrashaira'),
    ('shairal@simplesitecompany.com', 'Laki, Shaira Lyra "Shaira"', 'lakishairalyrashaira'),
    ('sherwin@simple.biz', 'Santos, Sherwin', 'santossherwin'),
    ('sheryld@simple.biz', 'Diano, Sheryl Aiza "Sheryl"', 'dianosherylaizasheryl'),
    ('stara@simple.biz', 'Abella, Esterlita I. "Star"', 'abellaesterlitaistar'),
    ('stephc@simple.biz', 'Canales, Mary Stiphanny "Steph"', 'canalesmarystiphannysteph'),
    ('stephc@simplesitecompany.com', 'Canales, Mary Stiphanny "Steph"', 'canalesmarystiphannysteph'),
    ('syr@simple.biz', 'Rosal, Isabelle "Sy"', 'rosalisabellesy'),
    ('talat@simple.biz', 'Tia, Cristal Joyce "Tala"', 'tiacristaljoycetala'),
    ('tinb@simple.biz', 'Bumagat, Khristine G. "Tin"', 'bumagatkhristinegtin'),
    ('tinem@simple.biz', 'Malazarte, Justine Marie Evette "Tine"', 'malazartejustinemarieevettetine'),
    ('tinz@simple.biz', 'Zambra, Ma.Justine "Tin"', 'zambramajustinetin'),
    ('tinz@simplesitecompany.com', 'Zambra, Ma.Justine "Tin"', 'zambramajustinetin'),
    ('tobic@simple.biz', 'Cadag, Tobi "Tobi"', 'cadagtobitobi'),
    ('tonc@simple.biz', 'Caceres, Clinton "Ton"', 'caceresclintonton'),
    ('tonrayc@simple.biz', 'Caldoza,Tonray "Ray"', 'caldozatonrayray'),
    ('ulyg@simple.biz', 'Galagnara, Ulysses "Uly"', 'galagnaraulyssesuly'),
    ('vanessac@simple.biz', 'Cultura, Vanessa "Vanessa"', 'culturavanessavanessa'),
    ('vanessad@simple.biz', 'Delgado, Vanessa Mae', 'delgadovanessamae'),
    ('vanp@simple.biz', 'Patigayon, Evander "Van"', 'patigayonevandervan'),
    ('veec@simple.biz', 'Mortos, Veronela Clarissa "Vee"', 'mortosveronelaclarissavee'),
    ('verag@simple.biz', 'Giducos, Vera "Vera"', 'giducosveravera'),
    ('vinzm@simple.biz', 'Medina, Vince Hubert "Vinz"', 'medinavincehubertvinz'),
    ('wilf@simple.biz', 'Fernandez, Wilfredo Jr "Wil"', 'fernandezwilfredojrwil'),
    ('zaka@simple.biz', 'Asackil, Aguell "Zak"', 'asackilaguellzak'),
    ('zyberb@simple.biz', 'Bioneda, Zyber Jison "Zyber"', 'bionedazyberjisonzyber')
),

-- Compute a normalized name key for every Hogan Smith Law master row, then
-- join it to the sheet by that key. Pick a single sheet email per name_key
-- (DISTINCT ON) so we never try to write two values into one master row.
master_match AS (
  SELECT DISTINCT ON (m.ctid)
    m.ctid                                            AS master_ctid,
    m."Work Email"                                    AS current_work_email,
    s.work_email                                      AS new_work_email
  FROM global_master_list m
  JOIN sheet s
    ON regexp_replace(lower(coalesce(m."Name", '')), '[^a-z0-9]', '', 'g') = s.name_key
  WHERE m."Department" = 'Hogan Smith Law'
    AND (m."Work Email" IS NULL
         OR lower(trim(m."Work Email")) IS DISTINCT FROM s.work_email)
),

-- Dry-run preview: how many master rows we'd change, and examples
preview AS (
  SELECT
    (SELECT COUNT(*) FROM master_match)                              AS master_rows_to_update,
    (SELECT array_agg((current_work_email, new_work_email))
       FROM (SELECT * FROM master_match LIMIT 10) t)                 AS sample_pairs
)
SELECT * FROM preview;
