-- ============================================================================
-- HR onboarding staging table — `hr_pending_employees`
-- Generated: 2026-05-08
--
-- Purpose
--   New hires entered through the HR Dashboard ("Add person" flow) land here
--   first. They are NOT visible to any other dashboard until HR explicitly
--   "promotes" the row, which copies the entry into `global_master_list` and
--   stamps the row with the current `master_list_uploads.id` so it appears in
--   the `active_employees` view.
--
--   Why a staging table instead of writing directly to `global_master_list`:
--     • The master list is reconciled by CSV uploads (see
--       global-master-list-db.ts → replaceGlobalMasterListFromCsvText).
--       A row that is NOT in the next CSV drops out of `active_employees`.
--     • Staging lets HR collect new-hire info as it arrives (interview, work
--       email coming from Payroll on Friday, orientation confirmation on
--       Monday) before committing to the master list.
--     • Cancelling or correcting a draft is cheap; rolling back a master-list
--       edit is not.
--
-- Lifecycle
--   pending_work_email  → row created without an @simple.biz address
--   ready               → all fields populated, awaiting HR confirmation
--   promoted            → copied into global_master_list (read-only after this)
--   cancelled           → withdrawn before promotion (kept for audit)
--
-- Promotion
--   On promotion the server route inserts a corresponding row into
--   `global_master_list` with first_seen_upload_id = last_seen_upload_id =
--   current upload, then sets `promoted_at` + `promoted_to_master_id` here.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.hr_pending_employees (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by    TEXT,                          -- email of the HR user that filed it
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Identity ──────────────────────────────────────────────────────────────
  name              TEXT NOT NULL,
  personal_email    TEXT NOT NULL,
  work_email        TEXT,                      -- nullable — populated when Payroll mints @simple.biz
  department        TEXT NOT NULL,
  job_description   TEXT,

  -- Schedule + sourcing ───────────────────────────────────────────────────
  start_date        DATE,
  source            TEXT,                      -- where the hire came from (referral, agency, etc.)

  -- Contact ───────────────────────────────────────────────────────────────
  phone             TEXT,
  location          TEXT,                      -- free-text city / region for now

  -- Compensation (pre-filled from employee_hourly_rates by department) ────
  regular_rate      NUMERIC(10,2),
  ot_rate           NUMERIC(10,2),

  -- Workflow ──────────────────────────────────────────────────────────────
  status            TEXT NOT NULL DEFAULT 'pending_work_email'
                      CHECK (status IN ('pending_work_email','ready','promoted','cancelled')),
  notes             TEXT,

  -- Promotion bookkeeping (set when status flips to 'promoted') ───────────
  --   global_master_list.id is UUID in this deployment — match it.
  promoted_at              TIMESTAMPTZ,
  promoted_to_master_id    UUID REFERENCES public.global_master_list(id) ON DELETE SET NULL
);

-- Lookup indexes — list views filter by status; search hits email + name.
CREATE INDEX IF NOT EXISTS hr_pending_employees_status_idx
  ON public.hr_pending_employees (status);
CREATE INDEX IF NOT EXISTS hr_pending_employees_created_at_idx
  ON public.hr_pending_employees (created_at DESC);
CREATE INDEX IF NOT EXISTS hr_pending_employees_personal_email_idx
  ON public.hr_pending_employees (LOWER(personal_email));

COMMENT ON TABLE public.hr_pending_employees IS
  'HR staging area for new hires before they are promoted into global_master_list.';

-- updated_at maintenance trigger ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.touch_hr_pending_employees_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS hr_pending_employees_set_updated_at ON public.hr_pending_employees;
CREATE TRIGGER hr_pending_employees_set_updated_at
  BEFORE UPDATE ON public.hr_pending_employees
  FOR EACH ROW EXECUTE FUNCTION public.touch_hr_pending_employees_updated_at();

-- Verify ─────────────────────────────────────────────────────────────────
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'hr_pending_employees'
ORDER BY ordinal_position;
