-- ============================================================
-- Seed: Department column in employee_hourly_rates
-- Source: references/Global Master List.csv
-- Matched: 442 / 442 rows
-- Run in Supabase SQL Editor
-- ============================================================

-- Step 1: Add column if it does not already exist
ALTER TABLE employee_hourly_rates
  ADD COLUMN IF NOT EXISTS "Department" TEXT;

-- Step 2: Update each row with its department
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'lynnb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'daniellec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'shaie@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'april@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'ruthg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'kristinec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'jerrekl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'franm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'jupitero@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'darrellp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'juliar@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'joanas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'lenny@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'maryv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'ernstl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'kentshinw@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'argels@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'jvincec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'cobb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'kayserb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'jerup@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'francor@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'djr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'kaner@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'ryanr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'adriant@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jeannea@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'sheilac@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'louc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'dianad@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'aimberh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'gladysi@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'robinp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'angiep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'joanalyn@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'janes@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'julies@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'leaht@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'jigsv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'harrye@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Site Building' WHERE "Work Email" = 'johnf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Site Building' WHERE "Work Email" = 'bryanl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Site Building' WHERE "Work Email" = 'chrisr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Site Building' WHERE "Work Email" = 'joev@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'dond@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'kenl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'cjb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'christiant@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'cristalm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'jakes@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'jernalyni@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'acelip@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'dericl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'cargila@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'romera@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'vincentb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'jazc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'marcusc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'chrisd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'marjorie@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'alid@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'justinf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'ruffag@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'mikeh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'thiaj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'jan@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'riza@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'reenal@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'angelam@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'gotm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'maxm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'janem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'miguelm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'sharlaine@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'kobem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'adrianp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'janinep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'vanjohnp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'angelp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'johnp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'charmaineq@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'kennethr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'macd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'benr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'louier@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'warren@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'charless@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'jos@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Edit Team' WHERE "Work Email" = 'danicas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Site Building' WHERE "Work Email" = 'jazzies@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'ruthb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'julyb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'johnc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'johnryg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'chadg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'maum@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'cjm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'ellyt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'jamec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'jeffersoni@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'fayel@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'abigailv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'khasseyg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'nhyllc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'lorenab@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'bryann@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'maryo@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'mistyj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'fredj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'ruthm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'mikea@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'regu@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'vhanm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'arviev@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'justiner@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'mikel@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'migsr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'dandt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'camilleb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rachellen@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Callback Team' WHERE "Work Email" = 'jonathanv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rjq@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jeffj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'vernd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'edwardt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'tinf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jeanb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'myraf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'myke@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'chrisb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jennyr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'nerryd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'noreenb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'allif@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kits@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'josephrr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'christianf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'lancez@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'nancya@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'jaya@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rjaya@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'amielaa@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jayveea@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'matta@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'bela@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'angelicac@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'errola@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'exa@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'michaelb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'jpb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'danicab@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rochieb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'angelob@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'bryb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Accounting Team' WHERE "Work Email" = 'jeanneb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'ferdieb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'arcyb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'justineb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jonb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'alexb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'wendellb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'inac@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jaywlc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kevc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'marcc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jaypc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'geraldc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'simonr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'mayc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'aunicec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'arjayc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'aprilc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'julzc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'earlc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jingc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'shaunc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'harleyc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'solc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'dwightc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kevinc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'mitchc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'nield@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'alexr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'josephusd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jericc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'marcd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'echod@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'iked@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'clarad@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rennd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'gilbertd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'elie@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'alexe@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'vine@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'mykf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'dennisf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kristinf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'wilf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'ralphf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'johnrg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'berng@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'royg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'djg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'miguelg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'troyg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'jayg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'adrianeg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jhonh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jenh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'luckye@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'cji@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'yannai@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'jeni@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'lauricej@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'gracel@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'honeyl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kayl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'chrisl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'peterl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jomarl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'charlesl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'breyl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'fritzl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jaysonl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kayem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'francem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jaysonm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'johnm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'melm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'dazelm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'algiem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'andym@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jomsm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'pearlm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'ivanm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'khrism@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'markmo@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'jann@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'arvsn@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'vano@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jayarp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'joep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'cathyp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jullp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'jerryp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jordanp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'danp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jomp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'rainp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'patrickq@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'alfredc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'ricar@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'romr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'joer@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'janr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'dhear@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'nathanr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'clarizr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jesr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'joshr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'franzs@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'stacys@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'renards@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'joshuas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'alains@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jads@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'argylt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'maryt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'rrt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'shawnt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'jct@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'vincet@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'jeant@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'marcusu@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jenv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'michellev@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kerviev@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'maev@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'miela@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jayy@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'chrisz@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'james@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HSL' WHERE "Work Email" = 'markv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Orphan Ministry' WHERE "Work Email" = 'ralphm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'gary@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'jecka@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'jhonb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'russell@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'paul@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'joshua@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'scott@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'reid@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'ryan@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'lily@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'judy@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'joy@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'rexg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'andre@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'clangg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'jimg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'eugeneg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'iann@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'jone@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'khenl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'pearl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'brigitte@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'vincem@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'abbym@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'zn@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'karln@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'nancy@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'ken@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'genep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'audrey@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'imeer@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'john@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'lawrence@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'ralf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'steve@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'maggie@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'maria@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'SmartStaff' WHERE "Work Email" = 'kevin@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'joe@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'PM Team' WHERE "Work Email" = 'clintv@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'perryb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'samb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'ivyd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'joshuadc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'marilyn@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'maui@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'enzzy@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'aceo@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'shielar@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'QC' WHERE "Work Email" = 'jeromer@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'aleighshaa@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'markf@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'jcr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'deanm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'debm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'gladysp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'heartm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Sales' WHERE "Work Email" = 'larat@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'marka@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'marlond@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'nick@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'SmartStaff' WHERE "Work Email" = 'jerry@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'SmartStaff' WHERE "Work Email" = 'jed@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'issa@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'reia@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'kryzeln@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'SmartStaff' WHERE "Work Email" = 'gilt@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Social Media Team' WHERE "Work Email" = 'thea@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'courtney@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'thomas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'nicholas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'adrian@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'sterling@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Hogan Smith Law' WHERE "Work Email" = 'emma@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'US Manager Bonus' WHERE "Work Email" = 'seungyong@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'HR' WHERE "Work Email" = 'teal@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'US Manager Bonus' WHERE "Work Email" = 'jeff@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'US Manager Bonus' WHERE "Work Email" = 'carla@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'US Manager Bonus' WHERE "Work Email" = 'jackie@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'mitsa@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'marymm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'tina@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'christiana@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'shauln@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'dannat@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'sydneyr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'melanieg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'staceya@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'alisonc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'bena@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'jeana@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'arnoldb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'annb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'hansc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'talc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'raymondc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'shenc@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'lyrab@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'miguiellec@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'athenad@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'reyd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'joang@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'kend@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'charityg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'stepheng@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'crisj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'mikayi@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'clinti@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'SmartStaff' WHERE "Work Email" = 'ellye@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'russelm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'marym@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'hopen@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'rayo@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'beao@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'chariso@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'crizap@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'sharissp@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'janep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'jjr@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'hanss@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'shies@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'jennys@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'shielas@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'roxys@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'chrisw@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client - VA' WHERE "Work Email" = 'recheery@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Client VA' WHERE "Work Email" = 'rhysl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'karlm@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'ninap@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'faml@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'geln@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'glyzap@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'tinyn@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'olivet@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'laineh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'arriad@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'gile@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kennethb@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'gabg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'nikaelab@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'chrisg@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'nicoler@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'charlesd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'mishalgracet@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'kareno@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'risht@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'nicolep@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'elic@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'philu@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'roberts@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'beijayh@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'patd@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'alecj@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'paur@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Lead Gen' WHERE "Work Email" = 'jant@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'AI/API Team' WHERE "Work Email" = 'francisl@simple.biz';
UPDATE employee_hourly_rates SET "Department" = 'Discovery' WHERE "Work Email" = 'henrye@simple.biz';
