-- HSL team members seed (from 'Hogan Smith Team Members Rate and Bonus - Hogan Agents Pay Plan.csv')
-- Run in Supabase SQL editor. Idempotent: re-running updates existing rows.

CREATE TABLE IF NOT EXISTS public.hsl_team_members (
  email         text PRIMARY KEY,
  full_name     text,
  hsl_name      text,        -- the nickname column from the sheet
  role_raw      text,        -- original 'Department/ Role' string from CSV
  dept_key      text,        -- one of the HSL_DEPT_KEYS, NULL if outside the 13 KPI depts
  is_manager    boolean      NOT NULL DEFAULT false,
  hourly_rate   numeric(10,2),
  ot_rate       numeric(10,2),
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hsl_team_members_dept_idx ON public.hsl_team_members(dept_key);

INSERT INTO public.hsl_team_members (email, full_name, hsl_name, role_raw, dept_key, is_manager, hourly_rate, ot_rate) VALUES
  ('gyd@simple.biz', 'Tura, Gyd', 'Julie', 'Operations Manager', NULL, false, 500.00, 750.00),
  ('eulap@simple.biz', 'Pacheco, Eula Jane J.', 'Heather', 'Case Management Manager', 'case_mgmt_asst_tl', true, 425.00, 637.50),
  ('emss@simple.biz', 'Solon, Emily "Ems"', 'Emily', 'Pre-Hearing Manager', 'post_hearing_prep', true, 425.00, 637.50),
  ('stara@simple.biz', 'Abella, Esterlita I. "Star"', 'Esther', 'Post-Hearing Manager', 'post_hearing_prep', true, 425.00, 637.50),
  ('andret@simple.biz', 'Tolentino, Romel T. "Andre"', 'Andy', 'Filing Specialist Manager', 'filing_specialist', true, 425.00, 637.50),
  ('mariely@simple.biz', 'Yungco, Marielace "Mariel" Buena Fe', 'Mariel', 'Intake Specialist Manager', 'intake_specialist', true, 425.00, 637.50),
  ('jazzr@simple.biz', 'Redulla, Jazz', 'Jazz', 'Collections Manager', 'collections_tl', true, 425.00, 637.50),
  ('veec@simple.biz', 'Mortos , Veronela Clarissa "Vee"', 'Vicky', 'SSD Medical Records Manager', 'ssd_medical_records', true, 425.00, 637.50),
  ('arr@simple.biz', 'Rosales, Anna Rowella "AR"', 'Arya (AR)', 'Guest Services Manager', NULL, false, 425.00, 637.50),
  ('dana@simple.biz', 'Abad, Danilo Jr "Dan"', 'Niel', 'Intake Specialist Asst TL', 'intake_specialist', false, 355.00, 532.50),
  ('juliec@simple.biz', 'Credo, Julie Ann "Julie"', 'Anna', 'Intake Specialist Asst TL', 'intake_specialist', false, 355.00, 532.50),
  ('jayh@simple.biz', 'Hernandez, John Michael', 'Jay', 'Intake Specialist Asst TL', 'intake_specialist', false, 335.00, 502.50),
  ('lorar@simple.biz', 'Roflo, Elora Dawn Del Mundo "Lora"', 'Lora', 'Case Management Assistant Team Leader', 'case_mgmt_asst_tl', false, 355.00, 532.50),
  ('johnwp@simple.biz', 'Paule, John Westley "Westley"', 'Westley', 'Case Management Assistant Team Leader', 'case_mgmt_asst_tl', false, 355.00, 532.50),
  ('brixf@simple.biz', 'Flores, Brix Cougar "Brix"', 'Brix', 'Case Management Assistant Team Leader', 'case_mgmt_asst_tl', false, 355.00, 532.50),
  ('jeremyt@simple.biz', 'Tanajora, Jem', 'Jeremy', 'Case Management Assistant Team Leader', 'case_mgmt_asst_tl', false, 355.00, 532.50),
  ('irisb@simple.biz', 'Borgonia, Iris M.', 'Sam', 'Case Management Assistant Team Leader', 'case_mgmt_asst_tl', false, 355.00, 532.50),
  ('aremb@simple.biz', 'Badajos, Arem "Arem"', 'Arem', 'Filing Specialist Assistant Team Leader', 'filing_specialist', true, 355.00, 532.50),
  ('jazminer@simple.biz', 'Roa, Sajda "Jazmine"', 'Jazmine', 'Mail-Sorting Team Leader', NULL, false, 355.00, 532.50),
  ('amiea@simple.biz', 'Arbol, Amelou "Amie"', 'Amie', 'Rick''s Assistant', NULL, false, 355.00, 532.50),
  ('nics@simple.biz', 'Sornito, Nicole "Nic"', 'Nix', 'QC', NULL, false, 355.00, 532.50),
  ('jemm@simple.biz', 'Makiling, Jem', 'Jem', 'QC', NULL, false, 355.00, 532.50),
  ('acea@simple.biz', 'Arrieta, Ace "Ace"', 'Ace', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('ara@simple.biz', 'Breboneria, Ara "Ara"', 'Ara', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('ashleyb@simple.biz', 'Baragona, Aslamah "Ashley"', 'Ash', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('jenl@simple.biz', 'Lagos, Jennifer "Jen"', 'Barbara', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('annel@simple.biz', 'Victoria, Jichelle La "Anne"', 'Bella', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('vanessac@simple.biz', 'Cultura, Vanessa "Vanessa"', 'Blythe', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('brandong@simple.biz', 'Gonzales, Brandon Jay "Brandon"', 'Bryce', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('kathl@simple.biz', 'Lapure, Kathleen "Kath"', 'Cara', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('camillm@simple.biz', 'Mercado, Joyce Camill "Camill"', 'Cassie', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('chrise@simple.biz', 'Enriquez, Chris Chan "Chris"', 'Chris', 'Case Mangr', 'case_manager', false, 305.00, 457.50),
  ('chrism@simple.biz', 'Mamhot, Niño Christian A. "Chris"', 'Christian', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('dancp@simple.biz', 'Dan Carlo Pagharion "Dan"', 'Clark', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('cliffl@simple.biz', 'Lopez, Cliff Roven "Cliff''', 'Clifford', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('tonc@simple.biz', 'Caceres, Clinton "Ton"', 'Clint', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('linkm@simple.biz', 'Mamaril, Lincoln Gerard A "Link"', 'Conor', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('dales@simple.biz', 'Delos Santos,Dale "Dale"', 'Dale', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('elmob@simple.biz', 'Biol, Elmer "Elmo"', 'Elmo', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('johnl@simple.biz', 'Lagos, John Michael  "John"', 'George', 'Case Mangr', 'case_manager', false, 305.00, 457.50),
  ('mikep@simple.biz', 'Placia, Michael S "Mike"', 'Harris', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('hendryp@simple.biz', 'Pamatian, Hendry "Hendry"', 'Hendry', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('ivym@simple.biz', 'Antig, Ivy Marie', 'Ivy', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('jannj@simple.biz', 'Jumonong, Jann Andrei "Jann"', 'Jaden', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('josephinet@simple.biz', 'Torralba, Josephine', 'Jessica', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('joloe@simple.biz', 'Esguerra, Jolo Miguel "Jolo"', 'Jolo', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('janinec@simple.biz', 'Certeza, Janine M "Janine"', 'Josie', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('joyb@simple.biz', 'Baldonebro, Joycel "Joy"', 'Joy', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('juliane@simple.biz', 'Elevazo, Julian "Julian"', 'Julian', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('keithc@simple.biz', 'Cayosa, Keith Xavier Jonathan"Keith"', 'Jupiter', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('kayea@simple.biz', 'Agustin, Kaye Lanie Munoz', 'Kaye', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('kellyc@simple.biz', 'Canave, Melisa Kelly "Kelly"', 'Kelly', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('jebr@simple.biz', 'Ravanilla, Jeb Patrick  "Jeb"', 'Levi', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('mariec@simple.biz', 'Calugay, Catherine "Marga"', 'Marga', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('miket@simple.biz', 'Torres, Michael John "Mike"', 'Martin', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('mayi@simple.biz', 'Inggo, Maybelle "May"', 'May', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('mackp@simple.biz', 'Plugio, Joseph Michael "Mack"', 'McKinley', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('miaj@simple.biz', 'Benedictos, Miarela Javier "Mia"', 'Mia', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('karmina@simple.biz', 'Dulu, Maria Karmina "Mina"', 'Mina', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('mikekja@simple.biz', 'Agtag, Mike king jay Erano "Mike"', 'Morty', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('nadinec@simple.biz', 'Chavez, Nadine', 'Nadine', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('olie@simple.biz', 'Estanislao,  Olimar Ramos "Oli"', 'Oliver', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('queenb@simple.biz', 'Baguio, Queencis Eve "Queen"', 'Olivia', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('patv@simple.biz', 'Velasco, Patricia Mikaela "Pat"', 'Paige', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('josephr@simple.biz', 'Robles, Joseph "Joseph"', 'Phoenix', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('rend@simple.biz', 'Domingo, Mariren Sto Domingo "Ren"', 'Reece', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('lawrenced@simple.biz', 'David, Lawrence Francis "Lawrence"', 'Robin', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('rosed@simple.biz', 'Dente, Rosemary Joy "Rose"', 'Ruth', 'Case Mangr', 'case_manager', false, 305.00, 457.50),
  ('sarahf@simple.biz', 'Fantilagan, Sarah "Sarah "', 'Sarah', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('johannas@simple.biz', 'Sacedon, Johanna Grace "Johanna"', 'Summer', 'Case Mangr', 'case_manager', false, 305.00, 457.50),
  ('tobic@simple.biz', 'Cadag, Tobi "Tobi"', 'Toby', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('isaact@simple.biz', 'Tesalona, Isaac John "Isaac"', 'Zack', 'Case Manager', 'case_manager', false, 305.00, 457.50),
  ('applef@simple.biz', 'Fajardo, Apple Gay A "Apple"', 'Adele', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('mariettac@simple.biz', 'Candor, Marietta "May"', 'Charlotte', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('field@simple.biz', 'Deguito, Fiel', 'Frank', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('jamg@simple.biz', 'Guanzon, Jamaica "Jam" P', 'Jam', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('aja@simple.biz', 'Joralyn, Amorado "AJ"', 'Jana', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('donb@simple.biz', 'Q, Brandon "Don"', 'Peter', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('tinb@simple.biz', 'Bumagat, Khristine G "Tin"', 'Tina', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('joyq@simple.biz', 'Quesada, Rina Joy, Cana "Joy"', 'Jewel', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('mariberto@simple.biz', 'Ong, Maribert "Mary"', 'Blaire', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('jerryl@simple.biz', 'Langcuyan, Jerelee "Jerry"', 'Candice', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('clydem@simple.biz', 'Mangawang ,Clyde "Clyde"', 'Clyde', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('christiannr@simple.biz', 'Roa, Christian "Chris"', 'Conrad', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('danm@simple.biz', 'Masacote, Dan Kristoffer "Dan"', 'Desmond', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('cathd@simple.biz', 'Dublin, Catherine "Cath"', 'Destiny', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('erict@simple.biz', 'Teano, Ericson "Eric"', 'Eric', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('emill@simple.biz', 'De Leon, Emiliano "Emil"', 'Ethan', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('hannan@simple.biz', 'Nacional, Hanna Mae "Hanna"', 'Hanna', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('johnq@simple.biz', 'Querijero, John Rhiel', 'Jason', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('jdd@simple.biz', 'Dagatan, Jensen "JD"', 'JD', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('mickyr@simple.biz', 'Reynante, Micky Jenelyn A "Micky"', 'Jenelyn', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('carlo@simple.biz', 'Cabrera, Justine Carl "Carl"', 'Justin', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('inchetm@simple.biz', 'Marasigan, Ma. Victoria "Inchet"', 'Madison', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('beckyp@simple.biz', 'Pascual, Rebecca "Becky"', 'Rebecca', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('rockym@simple.biz', 'Macalinga, Rocky Jedd "Rocky"', 'Rocky', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('cathl@simple.biz', 'Llanes, Cathyrine "Cath"', 'Susan', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('nesm@simple.biz', 'Macajelos, Nessan "Nes”', 'Tim (Nes)', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('ulyg@simple.biz', 'Galagnara, Ulysses "Uly"', 'Uly', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('zyberb@simple.biz', 'Bioneda, Zyber Jison "Zyber"', 'Zara', 'Pre-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('jonj@simple.biz', 'Jaring, Jon Francis "Jon"', 'Francis', 'Hearing Prep Team-Mail Sorting', 'post_hearing_prep', false, 265.00, 397.50),
  ('maricorc@simple.biz', 'Cruz, Maricor Lorenzo "Marie"', 'Maricar', 'Hearing Prep Team-Mail Sorting', 'post_hearing_prep', false, 265.00, 397.50),
  ('richardm@simple.biz', 'Manuyag, Richard Angelo "Richard"', 'Rowan', 'Hearing Prep Team-Mail Sorting', 'post_hearing_prep', false, 265.00, 397.50),
  ('applee@simple.biz', 'Esguerra , Apple Kaye "Kaye"', 'Apple', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('elaizaha@simple.biz', 'Alcanzo, Elaizah', 'Eliza', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('elaz@simple.biz', 'Zaspa, Dionela Rose "Nela"', 'Ella', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('grahama@simple.biz', 'Alolod,  "Graham" Christopher P.', 'Graham', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('jms@simple.biz', 'Sarana, John Michael R "JM"', 'Jaxon', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('mariea@simple.biz', 'Fulleros, Marie Antonette "Marie"', 'Toni', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('ede@simple.biz', 'Espiritu, Edric "Ed"', 'Ed', 'Filing Specialist', 'filing_specialist', false, 265.00, 397.50),
  ('rafa@simple.biz', 'Andres, Rafael Angelo "Raf"', 'Apollo', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('judyannc@simple.biz', 'Canales,Judy Ann  "Judy"', 'Athena', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('crisc@simple.biz', 'Cañete, Ma. Crismae Mae "Cris"', 'Cristy', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('brianr@simple.biz', 'Rieta, Brian Joshua  "Brian"', 'Elijah', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('alenm@simple.biz', 'Mendoza, Alen', 'Ellon', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('robp@simple.biz', 'Pegorosa, Bel Robert "Rob"', 'Ken', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('francisf@simple.biz', 'Boybanting, Francis Jay "Francis"', 'Leo', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('gericog@simple.biz', 'Go, Gerico “Echo”', 'Echo', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('jhabbye@simple.biz', 'Erojo, Jessa "Jhabby"', 'Zoe', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('reuvent@simple.biz', 'Torsiende, Reuven John “RJ”', 'Raven', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('litoe@simple.biz', 'Estrada, Lito "Lito"', 'Luke', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('jamesm@simple.biz', 'Maumbas, James Harry Beltran "James"', 'Hale', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('carlc@simple.biz', 'Canque, John Carlo “Carl”', 'Colby', 'Filing Specialist', 'filing_specialist', false, 235.00, 352.50),
  ('carrenm@simple.biz', 'Maisling, Carren "Carren"', 'Camille', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('denylm@simple.biz', 'Manalo, Mary Denyl "Denyl"', 'Denice', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('maee@simple.biz', 'Eusebio, Ma. Eva "Mae"', 'Elaine', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('iant@simple.biz', 'Dela Torre, Ian Gabriel "Ian"', 'Gabriel', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('joeyf@simple.biz', 'Florendo, Joey Pulido "Joey"', 'Joey', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('joeg@simple.biz', 'Guinto, Benigno Jose "Joe"', 'Jordan', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('canetho@simple.biz', 'Oblea, Caneth "Caneth"', 'Kendie', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('kevincc@simple.biz', 'Calape, Kevin "Kevin"', 'Kevin', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('kayo@simple.biz', 'Ornopia, Kaysha "Kay"', 'Krista', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('ladys@simple.biz', 'Sereno, Lady Maye "Lady"', 'Lainey', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('nolianq@simple.biz', 'Quiatchon Nolian "Lian"', 'Liana', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('marylouc@simple.biz', 'Canete, Marylou "Marylou"', 'Luna', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('lyrahp@simple.biz', 'Panoy, Lyrah ‘Lyrah”', 'Lyrah', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('rizalloydp@simple.biz', 'Pagayon, Rizalloyd Miguel “Migs”', 'Miguel', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('niczm@simple.biz', 'Maaño, Nicole Dominique  "Nicz"', 'Nicole', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('nikkaj@simple.biz', 'Jumaoas, Nikka "Nikka"', 'Nikka', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('rame@simple.biz', 'Estillore, Ramil "Ram"', 'Ram', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('wynd@simple.biz', 'Durado, Wynnvie Rico "Wynn"', 'Whitney', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('marshalla@simple.biz', 'Antonio, Marcial Domingo "Marshall"', 'Marshall', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('marionb@simple.biz', 'Bañares, Marion Anthony "Marion"', 'Murphy', 'Attestation', 'filing_specialist', false, 235.00, 352.50),
  ('grey@hogansmith.com', 'Basman,Jehd Monsour "Jhed"', 'Grey', 'Executive Guest Services Team Captain', NULL, false, 355.00, 532.50),
  ('wilf@simple.biz', 'Fernandez, Wilfredo Jr "Will"', 'Will', 'Executive Guest Services Team Capt', NULL, false, 355.00, 532.50),
  ('angm@simple.biz', 'Morales, Angelyne "Ang"', 'Angel', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('brendap@simple.biz', 'Paguidopon, Brenda "Brenda"', 'Brenda', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('edwardt@simple.biz', 'Tahil, Edward Maverick "Edward"', 'Edward', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('arjayc@simple.biz', 'Carranza, Arjay E "Arjay"', 'Harry', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('kerviev@simple.biz', 'Villarino, Kervie Angel "Kervie"', 'Karen', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('kayem@simple.biz', 'Malabay, Kaye Niegel "Kaye"', 'Kylie', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('maryo@simple.biz', 'Obando, Mary Grace "Mary"', 'Mariah', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('monam@simple.biz', 'Manatad, Monaliza "Mona"', 'Mona', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('hano@simple.biz', 'Orozco, Han Antoine ”Han”', 'Anton', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('marissat@simple.biz', 'Taguinod, Marissa "Marissa"', 'Maurice', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('meriamy@simple.biz', 'Ytang, Meriam "Meriam"', 'Emery', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('gracec@simple.biz', 'Calaoa, Grace "Grace"', 'Grace', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('mikee@simple.biz', 'Ealdama, Jean Michael "Mike"', 'Bruno', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('liccac@simple.biz', 'Castillo, Noreen Licca "Licca"', 'Amber', 'Intake Specialist Team Captain', 'intake_specialist', false, 245.00, 367.50),
  ('beijayh@simple.biz', 'Halog, Beijay "Beijay"', 'Bill', 'Intake Specialist Team Captain', 'intake_specialist', false, 245.00, 367.50),
  ('natel@simple.biz', 'Lunar, Jonathan "Nate"', 'Joseph', 'Intake Specialist Team Captain', 'intake_specialist', false, 245.00, 367.50),
  ('sherwins@simple.biz', 'Santos, Sherwin', 'Scott', 'Intake Specialist Team Captain', 'intake_specialist', false, 245.00, 367.50),
  ('talat@simple.biz', 'Tia, Cristal Joyce "Tala"', 'Tala', 'Intake Specialist Team Captain', 'intake_specialist', false, 245.00, 367.50),
  ('drews@simple.biz', 'Soriano, Hendrew "Drew"', 'Adrian', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('aubreyt@simple.biz', 'Tulaña, Aubrey Joy "Aubrey"', 'Aubrey', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('francem@simple.biz', 'Magallon, Francis "France"', 'Avery', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('benc@simple.biz', 'Cahoy, Albenjie  "Ben"', 'Ben', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('blakeg@simple.biz', 'Guanzon, Bernard Gregory S "Blake"', 'Blake', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jayarp@simple.biz', 'Pagliawan, Orlando "Jayar"', 'Carter', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('khasseyg@simple.biz', 'Gahi, Kharessa "Khassey"', 'Cassandra', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('claudep@simple.biz', 'Punay, Claudine A "Claude"', 'Claude', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('rond@simple.biz', 'Dabasol, Maronn Dois "Ron"', 'Cole', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('gracea@simple.biz', 'Alacre, Loivem "Grace"', 'Dakota', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('danmp@simple.biz', 'Piedad, Dan Mark "Dan"', 'Danny', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('dennisg@simple.biz', 'Gripo, Dennis "Dennis"', 'Denver', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('domt@simple.biz', 'Tan, Dominic "Dom"', 'Dominic', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('duanec@simple.biz', 'De La Cruz, Duane "Duane"', 'Dwayne', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('eddiei@simple.biz', 'Eddie boy Infante', 'Edmond', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('mitchb@simple.biz', 'Briones, Michelle Marie "Mitch"', 'Emma', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('indic@simple.biz', 'Cali, Indira Benito "Indi"', 'Felicity', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('marcusu@simple.biz', 'Umpad, Marcus "Marcus"', 'Ford', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('febb@simple.biz', 'Bontuyan, Febie "Feb"', 'Fria', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('valp@simple.biz', 'Padilla, Valentino Fernan "Val"', 'Fritz', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('gile@simple.biz', 'Espinosa, Gil Marc "Gil"', 'Gilbert', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('mikez@simple.biz', 'Zalavarria, Michael "Mike"', 'Grant', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('kimg@simple.biz', 'Galo, Kim Harold "Kim"', 'Harold', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('fredj@simple.biz', 'Juaton, Siegfred "Fred"', 'Harvey', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('janinad@simple.biz', 'Janiña Dayaganon', 'Janine', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('joee@simple.biz', 'Estomante, Jopie "Joe"', 'Joe', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('villev@simple.biz', 'Viloria, Ville John "Ville"', 'Johnson', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jaywlc@simple.biz', 'Cabatingan, Mark Jaywl "Mark"', 'Jude', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('karlm@simple.biz', 'Mahusay, Karl Anton "Karl"', 'Karl', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('kimerl@simple.biz', 'Lauron, Kimer “Kim”', 'Knox', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('charlesd@simple.biz', 'Diego, Charles Vacil Tardo "Charles"', 'Lester', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('lanf@simple.biz', 'Fuertes, Lani', 'Lily', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('lincolnm@simple.biz', 'Moguies, Lincoln Eman', 'Lincoln', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jayveea@simple.biz', 'Aliser, Jayvee Lloyd "Jayvee"', 'Lloyd', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('luisd@simple.biz', 'Damasco, Luis "Luis"', 'Luis', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('markmo@simple.biz', 'Molarte, Mark', 'Mark', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('mikeyh@simple.biz', 'Hernandez, Michael "Mikey"', 'Mike', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('norwinb@simple.biz', 'Binas, Norwin "Norwin"', 'Nash', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('nikaa@simple.biz', 'Aldohueza Nika Alexis "Nika"', 'Natalie', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('philu@simple.biz', 'Uclaray, Phil Keaggy "Phil"', 'Phil', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('rainp@simple.biz', 'Postrano, Reynan "Rain"', 'Rain', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('renards@simple.biz', 'Seledio, Renard "Renard"', 'Renard', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('richardr@simple.biz', 'Rinon, Richard Ian "Richard"', 'Richie', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('emsg@simple.biz', 'Guce, Melliza Mae "Ems"', 'Sadie', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('alexb@simple.biz', 'Busano, Lorenzo "Alex"', 'Simon', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('kerlu@simple.biz', 'Uypico, Kerl "Kerl"', 'Sky', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('franzs@simple.biz', 'Franz Vincent Sancio "Franz"', 'Todd', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('trishc@simple.biz', 'Cirilo, Trisha Mae "Trish"', 'Trisha', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('wilburta@simple.biz', 'Alamo, Wilburt Jonas “Wilburt”', 'Wilburt', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('chelzyc@simple.biz', 'Chavez, Chelzy "Chelzy"', 'Chelzy', 'SSD Medical Records - 
Vicky''s Asst TL (Accounting)', 'ssd_medical_records', false, 355.00, 532.50),
  ('jeromea@simple.biz', 'Aguirre, Jerome G "Jerome"', 'Jerome', 'SSD Medical Records- Vicky''s Asst TL', 'vicky_asst_tl', true, 355.00, 532.50),
  ('noimeg@simple.biz', 'Gaspar, Noime "Noime"', 'Naomi', 'SSD Medical Records-Team Captain', 'ssd_medical_records', false, 285.00, 427.50),
  ('vanp@simple.biz', 'Patigayon, Evander "Van"', 'Van', 'SSD Medical Records-Team Captain', 'ssd_medical_records', false, 285.00, 427.50),
  ('ninac@simple.biz', 'Cruz, Nina Christina "Nina"', 'Nina', 'SSD Medical Records-Team Captain', 'ssd_medical_records', false, 285.00, 427.50),
  ('johnbv@simple.biz', 'Villanueva, John B "John"', 'Noah', 'SSD Medical Records-Team Captain', 'ssd_medical_records', false, 285.00, 427.50),
  ('nete@simple.biz', 'Ebardo, Carol "Net', 'Carol', 'SSD Medical Records-Team Captain', 'ssd_medical_records', false, 285.00, 427.50),
  ('angelc@simple.biz', 'Cosep, Angel Mae "Angel"', 'Alice', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('geloa@simple.biz', 'Abuel, Paul Angelo R. "Gelo"', 'Angelo', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('zaka@simple.biz', 'Asackil Aguell "Zak"', 'Ashton', 'SSD Medical Records-POC', 'ssd_medical_records', false, 265.00, 397.50),
  ('erjiee@simple.biz', 'Estolonio, Erjie "Erjie"', 'Bailey', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('cannys@simple.biz', 'Canny Rose Savillo "Canny"', 'Canny', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('carlylec@simple.biz', 'Cortes, Carlyle "Carlyle"', 'Carlyle', 'SSD Medical Records-POC', 'ssd_medical_records', false, 265.00, 397.50),
  ('cassiusc@simple.biz', 'Cortes, Cassius Clay E "Cassius"', 'Cassius', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('cindyg@simple.biz', 'Gonzales, Cindy "Cindy"', 'Cecilia', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('edryckm@simple.biz', 'Mira, Edryck Mae N "Ed"', 'Cedric', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('kimbr@simple.biz', 'Briones, Kim "Kim"', 'Chad', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('charlesc@simple.biz', 'Dela Cruz, Charles Kerzey "Charles"', 'Charles', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('cjc@simple.biz', 'Cortes, Cee Jei "CJ"', 'Claire', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('angeld@simple.biz', 'Dalusong, Angelica "Angel"', 'Dalia', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('jedp@simple.biz', 'Porquez Jeremy Jed "Jed"', 'Derek', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('dextert@simple.biz', 'Tagulinao, Ryan Dexter "Dexter"', 'Dexter', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('melvsf@simple.biz', 'Faeldan, Melvin "Melvs"', 'Emerald', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('edm@simple.biz', 'Mabaga, Edrown John "ED"', 'Ezra', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('guiaq@simple.biz', 'Quillosa, Guia Maria Mercado "Guia"', 'Gail', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('jomsa@simple.biz', 'Arce Jomar "Jom"', 'Gavin', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('gleng@simple.biz', 'Villanueva, Glenda "Glen"', 'Glenda', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('hannaa@simple.biz', 'Abad, Hannah Lynn "Hannah"', 'Hazel', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('jammers@simple.biz', 'Solijon, Jammer "Jam"', 'Jasper', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('jeriemym@simple.biz', 'Adove, Jeriemy Mckinly "Jeriemy"', 'Jerry', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('jaysond@simple.biz', 'Dao-ayan, Jayson O. "Jayson"', 'Jonas', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('marjunm@simple.biz', 'Macamay, Marjun "Marjun"', 'June', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('kailab@simple.biz', 'Benito, Mechaila "Kaila"', 'Kourtney', 'SSD Medical Records- Chelzy''s Asst', 'chelzy_asst', false, 265.00, 397.50),
  ('ralfp@simple.biz', 'Pamintuan, Joseph Ralf "Joe"', 'Liam', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('maddies@simple.biz', 'Sabado, Madison Lori L "Maddie"', 'Maddie', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('marjf@simple.biz', 'Marjorie Garcia Fernandez "Marj"', 'Maggie', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('miahl@simple.biz', 'Leosala , Nehemiah "Miah"', 'Matias', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('melchezedeks@simple.biz', 'Sumandang, Melchezedek "Mel"', 'Matthew', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('mayt@simple.biz', 'Tampos, Mae "May"', 'Maya', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('mikeb@simple.biz', 'Baillo, Jan Michael M "Mike"', 'Milton', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('ralphr@simple.biz', 'Ramirez, Ralph William "Ralph"', 'Ralph', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('reeds@simple.biz', 'Salvador, Reed Jensen "Rees"', 'Reed', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('rochelled@simple.biz', 'Dumlao, Rochelle Grace "Rochelle"', 'Rochelle', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('robt@simple.biz', 'Tantiado Rob "Rob"', 'Roland', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('rosep@simple.biz', 'Principe, Roses "Rose"', 'Rose', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('airahe@simple.biz', 'Estologa, Airah Sol D.  "Airah"', 'Scarlet', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('chet@simple.biz', 'Tecson, Ma. Theresa "Che"', 'Terry', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('roda@simple.biz', 'Alejandre , Girod "Rod"', 'Tino', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('tonrayc@simple.biz', 'Caldoza,Tonray "Ray"', 'Tracy', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('tinem@simple.biz', 'Malazarte, Justine Marie Evette "Tine"', 'Trina', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('janp@simple.biz', 'V-Jan Del Prado "Jan"', 'Vera', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('aprill@simple.biz', 'Lapaz, April "April"', 'Verbane', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('markd@simple.biz', 'Descalzo, Mark Vincent', 'Vince', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('vinzm@simple.biz', 'Medina, Vince Hubert "Vinz"', 'Vincent', 'SSD Medical Records', 'ssd_medical_records', false, 265.00, 397.50),
  ('ruffamaeg@simple.biz', 'Generalao, Ruffa Mae  "Ruffa"', 'Winter', 'SSD Medical Records-POC', 'ssd_medical_records', false, 265.00, 397.50),
  ('andym@simple.biz', 'Manzano, Andy "Andy"', 'Aaron', 'Collection', 'collections', false, 265.00, 397.50),
  ('alexe@simple.biz', 'Evangelista, Alexander', 'Alex', 'Collection', 'collections', false, 265.00, 397.50),
  ('algiem@simple.biz', 'Manzano, Algie Anne R "Algie"', 'Amanda', 'Collection', 'collections', false, 265.00, 397.50),
  ('anng@simple.biz', 'Gevido, Annrose "Ann"', 'Annie', 'Collection', 'collections', false, 265.00, 397.50),
  ('aprilc@simple.biz', 'Carriaga, April Mae "April"', 'April', 'Collection', 'collections', false, 265.00, 397.50),
  ('arvsn@simple.biz', 'Navarro, Arvin "Arvs"', 'Arvin', 'Collection', 'collections', false, 265.00, 397.50),
  ('aura@simple.biz', 'Ibañez, Auraluz A. "Aura"', 'Aura', 'Collection', 'collections', false, 265.00, 397.50),
  ('argylt@simple.biz', 'Tabula, Argyl "Argyl"', 'Aurora', 'Collection', 'collections', false, 265.00, 397.50),
  ('jaket@simple.biz', 'Tapere, John Benedict "Jake"', 'Benedict', 'Collection', 'collections', false, 265.00, 397.50),
  ('ferdieb@simple.biz', 'Bondoc, Ferdinand "Ferdie"', 'Bradley', 'Collection', 'collections', false, 265.00, 397.50),
  ('breen@simple.biz', 'Nalangan, Aubrey Therese "Bree"', 'Bree', 'Collection', 'collections', false, 265.00, 397.50),
  ('choloh@simple.biz', 'Hernandez, Cholo "Cholo"', 'Charlie', 'Collection', 'collections', false, 265.00, 397.50),
  ('clarizr@simple.biz', 'Rosales, Clariza Mae  "Clariz"', 'Clariz', 'Collection', 'collections', false, 265.00, 397.50),
  ('mariam@simple.biz', 'Magallano, Maria Corazon "Maria"', 'Cora', 'Collection', 'collections', false, 265.00, 397.50),
  ('melm@simple.biz', 'Manalo, Armel D. "Mel"', 'Hunter', 'Collection', 'collections', false, 265.00, 397.50),
  ('kennm@simple.biz', 'Melliza , Kenneth "Ken"', 'Ivan', 'Collection', 'collections', false, 265.00, 397.50),
  ('jct@simple.biz', 'Tembrina, John Carlo "JC"', 'Jace', 'Collection', 'collections', false, 265.00, 397.50),
  ('jeni@simple.biz', 'Ipili, Lynie Jane "Jen"', 'Jane', 'Collection', 'collections', false, 265.00, 397.50),
  ('jeant@simple.biz', 'Tupas, Honey Jean "Jean"', 'Jean', 'Collection', 'collections', false, 265.00, 397.50),
  ('josephf@simple.biz', 'Florita, Joseph Anthony "Joseph"', 'Josh', 'Collection', 'collections', false, 265.00, 397.50),
  ('khrism@simple.biz', 'Moises, Khrisna "Khris"', 'Krissa', 'Collection', 'collections', false, 265.00, 397.50),
  ('angelicac@simple.biz', 'Angelica Concepcion, "Angel"', 'Lila', 'Collection', 'collections', false, 265.00, 397.50),
  ('lovelyc@simple.biz', 'Celis, Lovely V "Love"', 'Lovely', 'Collection', 'collections', false, 265.00, 397.50),
  ('mackyj@simple.biz', 'Jordan, Reymark Japon "Macky"', 'Malcolm', 'Collection', 'collections', false, 265.00, 397.50),
  ('markv@simple.biz', 'Villarba, Mark Anthony "Mark"', 'Marcus', 'Collection', 'collections', false, 265.00, 397.50),
  ('michaelb@simple.biz', 'Bacalla, Michael Ryan "MIchael"', 'Miles', 'Collection', 'collections', false, 265.00, 397.50),
  ('lauricej@simple.biz', 'Justiniane, Laurice Monette, C "Laurice"', 'Molly', 'Collection', 'collections', false, 265.00, 397.50),
  ('nerryd@simple.biz', 'Deloria, Nerry Mae "Nerry"', 'Nerry', 'Collection', 'collections', false, 265.00, 397.50),
  ('royg@@simple.biz', 'Giducos, Roy', 'Royce', 'Collection', 'collections', false, 265.00, 397.50),
  ('syr@simple.biz', 'Rosal, Isabelle "Sy"', 'Shane', 'Collection', 'collections', false, 265.00, 397.50),
  ('bela@simple.biz', 'Anastacio, Lovella "Belle"', 'Shelby', 'Collection', 'collections', false, 265.00, 397.50),
  ('stephc@simple.biz', 'Canales, Mary Stiphanny "Steph"', 'Steph', 'Collection', 'collections', false, 265.00, 397.50),
  ('jaya@simple.biz', 'Aguado, Jayson "Jay”', 'Tyler', 'Collection', 'collections', false, 265.00, 397.50),
  ('jcp@simple.biz', 'Pascual, John Christopher "JC"', 'JC', 'Care Team', 'care_team', false, 265.00, 397.50),
  ('ruffag@simple.biz', 'Gallego, Ruffa Mae "Ruffa"', 'Ruffa', 'Care Team', 'care_team', false, 265.00, 397.50),
  ('jakej@simple.biz', 'Jackson, Jacob John "Jake"', 'Jake', 'Healhcare Team-Team Leader', 'healthcare_team_lead', true, 355.00, 532.50),
  ('lovelyb@simple.biz', 'Bacarat, Lovely ‘Lai”', 'Leah', 'Healhcare Team', 'care_team', false, 265.00, 397.50),
  ('angelicai@simple.biz', 'Igbalic, Angelica', 'Angelica', 'Dan Smith EA- Med Rec', NULL, false, 265.00, 397.50),
  ('vanessad@simple.biz', 'Delgado, Vanessa Mae', 'Vanessa Mae', 'Dan Smith EA', NULL, false, 265.00, 397.50),
  ('cherylt@simple.biz', 'Tolero, Cheryl Lee Bandala "Cheryl"', 'Cherry', 'Executive Guest Services', NULL, false, 355.00, 532.50),
  ('neliab@simple.biz', 'Boiser Nelia "Nelia"', 'Nelia', 'Collection', 'collections', false, 265.00, 397.50),
  ('roses@simple.biz', 'Sardan, Rosemarie Marquez "Rose"', 'Daisy', 'Post-Hearing Prep Team', 'post_hearing_prep', false, 265.00, 397.50),
  ('loriem@simple.biz', 'San Mateo, Lorie Ann "Lorie"', 'Lorie', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('markg@simple.biz', 'Gomez, Mark Ryan “Mark”', 'Ryzen', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jakem@simple.biz', 'Malabago, Jake Kim "Jake"', 'Peyton', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jamesc@simple.biz', 'Chan, James Edward "James"', 'Japhet', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('kurtd@simple.biz', 'Duque, Kurt Steven ‘Kurt”', 'Kurt', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('loiso@simple.biz', 'Ortega, Rela Lois "Lois"', 'Lauren', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('diana@simple.biz', 'Alcalde, Dian Marie  "Dian"', 'Marian', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('michelled@simple.biz', 'Divinagracia, Michelle  "Michelle"', 'Mitch', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50),
  ('jetb@simple.biz', 'Bugarin, Jet Paul Bugarin "Jet"', 'Paul', 'Intake Specialist', 'intake_specialist', false, 225.00, 337.50)
ON CONFLICT (email) DO UPDATE SET
  full_name   = EXCLUDED.full_name,
  hsl_name    = EXCLUDED.hsl_name,
  role_raw    = EXCLUDED.role_raw,
  dept_key    = EXCLUDED.dept_key,
  is_manager  = EXCLUDED.is_manager,
  hourly_rate = EXCLUDED.hourly_rate,
  ot_rate     = EXCLUDED.ot_rate,
  updated_at  = now();

-- Audit:
--   SELECT dept_key, count(*) FROM public.hsl_team_members GROUP BY dept_key ORDER BY 2 DESC;
