-- ============================================================================
-- HRIS Updates — Kanban ticket board  (2026-07-15)
--
-- One shared board (Azure-DevOps style) where Accounting / HR / Managers /
-- CEO file "what we want changed in the HRIS" tickets and drag them across
-- four columns: To Do → In Progress → Testing → Done. Each ticket carries an
-- "Updates" reply thread (`ticket_comments`). Reached at /tickets on the main
-- app and via the hris-updates.vercel.app short link (proxy redirect).
--
-- Access model: the standard two layers —
--   * roles (accounting / hr_coordinator / manager / ceo / admin) open /tickets
--   * the `tickets` feature key in employee_feature_permissions decides per
--     user whether they can create/move tickets (`edit`) or just watch
--     (`view`). Admin toggles this in Admin → Roles & permissions.
--
-- ⚠️ RUN ORDER: deploy the new code first, then run this. Idempotent.
-- ============================================================================

BEGIN;

-- 1. tickets — the board items. `ticket_no` is the human-facing #id (like an
--    Azure DevOps work item id). `position` orders cards inside a column
--    (fractional indexing: the app writes midpoints on drag, no mass renumber).
CREATE TABLE IF NOT EXISTS public.tickets (
  id            uuid          primary key default gen_random_uuid(),
  ticket_no     bigint        generated by default as identity,
  title         text          not null,
  description   text,
  status        text          not null default 'todo'
                              check (status in ('todo','in_progress','testing','done')),
  priority      text          not null default 'medium'
                              check (priority in ('low','medium','high','urgent')),
  position      double precision not null default 0,
  created_by    text          not null,           -- work email (lowercased by trigger)
  created_by_name text,
  assigned_to   text,                             -- optional work email
  created_at    timestamptz   not null default now(),
  updated_at    timestamptz   not null default now()
);

-- 1b. Upgrade path: if an earlier run created the table with the original
--     New/Active/Resolved/Closed statuses, remap rows and swap the constraint.
--     No-op on a fresh install (the CASE matches nothing, the constraint is
--     recreated identically).
ALTER TABLE public.tickets DROP CONSTRAINT IF EXISTS tickets_status_check;
UPDATE public.tickets SET status = CASE status
  WHEN 'new'      THEN 'todo'
  WHEN 'active'   THEN 'in_progress'
  WHEN 'resolved' THEN 'testing'
  WHEN 'closed'   THEN 'done'
  ELSE status END
WHERE status IN ('new','active','resolved','closed');
ALTER TABLE public.tickets
  ADD CONSTRAINT tickets_status_check
  CHECK (status IN ('todo','in_progress','testing','done'));
ALTER TABLE public.tickets ALTER COLUMN status SET DEFAULT 'todo';

CREATE UNIQUE INDEX IF NOT EXISTS tickets_ticket_no_uniq ON public.tickets (ticket_no);
CREATE INDEX IF NOT EXISTS tickets_status_position_idx ON public.tickets (status, position);
CREATE INDEX IF NOT EXISTS tickets_created_by_idx ON public.tickets (lower(created_by));

-- 1c. ticket_comments — the "Updates" reply thread under each ticket. Replies
--     are immutable once posted (no edit/delete in the UI), so no updated_at.
CREATE TABLE IF NOT EXISTS public.ticket_comments (
  id            uuid          primary key default gen_random_uuid(),
  ticket_id     uuid          not null references public.tickets(id) on delete cascade,
  body          text          not null,
  author_email  text          not null,          -- work email (lowercased by trigger)
  author_name   text,
  created_at    timestamptz   not null default now()
);
CREATE INDEX IF NOT EXISTS ticket_comments_ticket_idx
  ON public.ticket_comments (ticket_id, created_at);

-- ── Touch trigger (bump updated_at on every write) ────────────────────────────
CREATE OR REPLACE FUNCTION public.tickets_touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tickets_touch ON public.tickets;
CREATE TRIGGER tickets_touch
  BEFORE INSERT OR UPDATE ON public.tickets
  FOR EACH ROW EXECUTE FUNCTION public.tickets_touch_updated_at();

-- ── Normalize email columns on write (defense; app also lowers) ───────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'normalize_email_column') THEN
    DROP TRIGGER IF EXISTS tickets_normalize_created_by ON public.tickets;
    CREATE TRIGGER tickets_normalize_created_by
      BEFORE INSERT OR UPDATE ON public.tickets
      FOR EACH ROW EXECUTE FUNCTION public.normalize_email_column('created_by');

    DROP TRIGGER IF EXISTS ticket_comments_normalize_author ON public.ticket_comments;
    CREATE TRIGGER ticket_comments_normalize_author
      BEFORE INSERT OR UPDATE ON public.ticket_comments
      FOR EACH ROW EXECUTE FUNCTION public.normalize_email_column('author_email');
  END IF;
END$$;

-- ── Expose to Realtime so boards + open reply threads update live ─────────────
DO $$
DECLARE t text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['tickets','ticket_comments'] LOOP
      IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t
      ) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
END$$;

-- 2. Seed the `tickets` feature grant for everyone who ALREADY holds one of the
--    board roles. New role grants auto-provision it (FEATURE_CATALOG), but
--    existing holders have no row and the overlay is default-deny — without
--    this they'd open /tickets and see nothing. Everyone starts at `edit`
--    (can create + drag); the admin downgrades individuals to `view`/hidden
--    in Admin → Roles & permissions.
INSERT INTO public.employee_feature_permissions (work_email, view_key, feature, access, granted_by)
SELECT DISTINCT
  lower(er.work_email),
  rv.view_key,
  'tickets',
  'edit',
  'migration:2026-07-15_tickets_kanban'
FROM public.employee_roles er
JOIN (VALUES
  ('accounting',     'accounting'),
  ('hr_coordinator', 'hr'),
  ('manager',        'manager'),
  ('ceo',            'ceo')
) AS rv(role, view_key) ON rv.role = er.role
WHERE er.revoked_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.employee_feature_permissions p
    WHERE lower(p.work_email) = lower(er.work_email)
      AND p.view_key = rv.view_key
      AND p.feature  = 'tickets'
      AND p.revoked_at IS NULL
  );

COMMIT;

-- Verify:
--   SELECT tablename FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename IN ('tickets','ticket_comments');
--   SELECT view_key, access, count(*) FROM employee_feature_permissions
--     WHERE feature='tickets' AND revoked_at IS NULL GROUP BY 1,2;
