-- Seed Hogan employees into employee_hourly_rates + global_master_list.
-- Gap-fill only: inserts where email missing; fills blank rate columns on existing rows.
-- Email normalization triggers will lowercase/trim on INSERT.

WITH staging(work_email, personal_email, name, department, regular_rate, ot_rate) AS (
  VALUES
    ('acea@simple.biz', 'acearrieta30@gmail.com', 'Arrieta, Ace "Ace"', 'Hogan Smith Law', 305.0, 320),
    ('airahe@simple.biz', 'airahsolestologa99@gmail.com', 'Estologa, Airah Sol D.  "Airah"', 'Hogan Smith Law', 265.0, 280),
    ('aja@simple.biz', 'runasfastasyoucan101@gmail.com', 'Amorado, Joralyn "AJ"', 'Hogan Smith Law', 265.0, 280),
    ('alainp@simple.biz', 'pequealain61@gmail.com', 'Peque, John Alain Ezron M. "Alain"', 'Hogan Smith Law', 235.0, 250),
    ('alb@simple.biz', 'albernbutantan@gmail.com', 'Butantan, Albern "Al"', 'Hogan Smith Law', 235.0, 250),
    ('alenm@simple.biz', 'alenmndz632@gmail.com', 'Mendoza  Xerxis Alen "Alen"', 'Hogan Smith Law', 235.0, 250),
    ('alexb@simple.biz', 'busanoloren@gmail.com', 'Busano, Lorenzo "Alex"', 'Hogan Smith Law', 305.0, 320),
    ('alexb@simplesitecompany.com', 'busanoloren@gmail.com', 'Busano, Lorenzo "Alex"', 'Hogan Smith Law', 305.0, 320),
    ('alexe@simple.biz', 'agot615@gmail.com', 'Evangelista, Alexander "Alex"', 'Hogan Smith Law', 355.0, 370),
    ('alexr@simple.biz', 'iyo.derama.1985@gmail.com', 'De Rama, Rufio Alexander "Alex"', 'Hogan Smith Law', 225.0, 240),
    ('algiem@simple.biz', 'algiemanzano026@gmail.com', 'Manzano, Algie Anne R "Algie"', 'Hogan Smith Law', 235.0, 250),
    ('amiea@simple.biz', 'contact.amiearbol@gmail.com', 'Arbol, Amelou "Amie"', 'Hogan Smith Law', 355.0, 370),
    ('andret@simple.biz', 'romtolentino97@gmail.com', 'Tolentino, Romel T. "Andre"', 'Hogan Smith Law', 425.0, 440),
    ('andrewg@simple.biz', 'ajitrey5@gmail.com', 'Gersaniba, Andrew "Andrew"', 'Hogan Smith Law', 265.0, 280),
    ('andrewg@simplesitecompany.com', 'ajitrey5@gmail.com', 'Gersaniba, Andrew "Andrew"', 'Hogan Smith Law', 305.0, 320),
    ('andrewma@simple.biz', 'jmilton19072011@gmail.com', 'Manteza, Andrew "Andrew"', 'Hogan Smith Law', 305.0, 320),
    ('andym@simple.biz', 'andymanzano2019@gmail.com', 'Manzano, Andy "Andy"', 'Hogan Smith Law', 235.0, 250),
    ('andym@simplesitecompany.com', 'andymanzano2019@gmail.com', 'Manzano, Andy "Andy"', 'Hogan Smith Law', 235.0, 250),
    ('angelc@simple.biz', 'amcosep1997@gmail.com', 'Cosep, Angel Mae "Angel"', 'Hogan Smith Law', 265.0, 280),
    ('angeld@simple.biz', 'angelicadalusong0402@gmail.com', 'Dalusong, Angelica "Angel"', 'Hogan Smith Law', 265.0, 280),
    ('angelicai@simple.biz', 'jiaigreturn@gmail.com', 'Igbalic, Angelica', 'Hogan Smith Law', 265.0, 280),
    ('annel@simple.biz', 'jlavictoria0427@gmail.com', 'La Victoria, Jichelle "Anne"', 'Hogan Smith Law', 305.0, 320),
    ('anng@simple.biz', 'annrosegevido27@gmail.com', 'Gevido, Annrose "Ann"', 'Hogan Smith Law', 265.0, 280),
    ('applee@simple.biz', 'applekayeesguerra@gmail.com', 'Esguerra, Apple Kaye "Kaye"', 'Hogan Smith Law', 265.0, 280),
    ('applef@simple.biz', 'applegayfajardo@gmail.com', 'Fajardo, Apple Gay A "Apple"', 'Hogan Smith Law', 265.0, 280),
    ('aprilc@simple.biz', 'aprilcarr0404@gmail.com', 'Carriaga, April Mae "April"', 'Hogan Smith Law', 305.0, 320),
    ('aprill@simple.biz', 'lezgolezgoo@gmail.com', 'Lapaz, April "April"', 'Hogan Smith Law', 265.0, 280),
    ('ara@simple.biz', 'breboneriaara@gmail.com', 'Breboneria, Ara "Ara"', 'Hogan Smith Law', 305.0, 320),
    ('arcd@simple.biz', 'arcturusddordas@gmail.com', 'Dordas, Arcturus "Arc"', 'Hogan Smith Law', 235.0, 250),
    ('aremb@simple.biz', 'arembadajos@gmail.com', 'Badajos, Arem "Arem"', 'Hogan Smith Law', 265.0, 280),
    ('arr@simple.biz', 'annarowellarosales@gmail.com', 'Rosales, Anna Rowella "AR"', 'Hogan Smith Law', 355.0, 370),
    ('artp@simple.biz', 'kuchintaaa@gmail.com', 'Plaza, Art Jr.  "Art"', 'Hogan Smith Law', 225.0, 240),
    ('arvsn@simple.biz', 'nivra.orravan1984@gmail.com', 'Navarro, Arvin "Arvs"', 'Hogan Smith Law', 225.0, 240),
    ('ashleyb@simple.biz', 'aslamah.esmael@gmail.com', 'Baragona, Aslamah "Ashley"', 'Hogan Smith Law', 305.0, 320),
    ('aubreyt@simple.biz', 'breajoy22@gmail.com', 'Tulaña, Aubrey Joy "Aubrey"', 'Hogan Smith Law', 225.0, 240),
    ('aurai@simple.biz', 'aura.ibanez02@gmail.com', 'Ibañez, Auraluz A. "Aura"', 'Hogan Smith Law', 265.0, 280),
    ('beao@simple.biz', 'beapatriciaolarte@gmail.com', 'Olarte, Bea Patricia  "Bea"', 'Hogan Smith Law', 305.0, 320),
    ('beckyp@simple.biz', 'chinkypascual17@gmail.com', 'Pascual, Rebecca "Becky"', 'Hogan Smith Law', 265.0, 280),
    ('bela@simple.biz', 'belle.ramos1019@gmail.com', 'Anastacio, Lovella "Belle"', 'Hogan Smith Law', 305.0, 320),
    ('benc@simple.biz', 'cahoyalbenjie@yahoo.com', 'Cahoy, Albenjie "Ben"', 'Hogan Smith Law', 355.0, 370),
    ('brandong@simple.biz', 'brandonbauzon94@gmail.com', 'Gonzales, Brandon Jay "Brandon"', 'Hogan Smith Law', 305.0, 320),
    ('breen@simple.biz', 'theresenalangan@gmail.com', 'Nalangan, Aubrey Therese "Bree"', 'Hogan Smith Law', 265.0, 280),
    ('brianr@simple.biz', 'rietajo@yahoo.com', 'Rieta, Brian Joshua  "Brian"', 'Hogan Smith Law', 235.0, 250),
    ('brixf@simple.biz', 'briflores999@gmail.com', 'Flores, Brix Cougar "Brix"', 'Hogan Smith Law', 355.0, 370),
    ('camillm@simple.biz', 'camillmercado05@gmail.com', 'Mercado, Joyce Camill "Camill"', 'Hogan Smith Law', 305.0, 320),
    ('cannys@simple.biz', 'cassidee1207@gmail.com', 'Savillo, Canny Rose  "Canny"', 'Hogan Smith Law', 265.0, 280),
    ('carlb@simple.biz', 'carlbernardo10201981@gmail.com', 'Bernardo, Carl Phillip "Carl"', 'Hogan Smith Law', 235.0, 250),
    ('carlo@simple.biz', 'zith071030@gmail.com', 'Cabrera, Justine Carl "Carl"', 'Hogan Smith Law', 265.0, 280),
    ('carlylec@simple.biz', 'carlylecorteselectona@gmail.com', 'Cortes, Carlyle "Carlyle"', 'Hogan Smith Law', 265.0, 280),
    ('cathd@simple.biz', 'catherine.dublin.va@gmail.com', 'Dublin, Catherine "Cath"', 'Hogan Smith Law', 265.0, 280),
    ('cathl@simple.biz', 'cathyrinellanes08@gmail.com', 'Llanes, Cathyrine "Cath"', 'Hogan Smith Law', 265.0, 280),
    ('cathys@simple.biz', 'Cathyrina0715@gmail.com', 'Siochi, Catherine Rina "Cathy"', 'Hogan Smith Law', 265.0, 280),
    ('cessp@simple.biz', 'cessperez0012@gmail.com', 'Perez, Princess Joan "Cess"', 'Hogan Smith Law', 235.0, 250),
    ('charlesc@simple.biz', 'cdcruz22@hotmail.com', 'Dela Cruz, Charles Kerzey "Charles"', 'Hogan Smith Law', 265.0, 280),
    ('charmd@simple.biz', 'cdeleverio1995@gmail.com', 'Deleverio, Charmaine "Charm"', 'Hogan Smith Law', 225.0, 240),
    ('chaseg@simple.biz', 'chaseslugger1107@gmail.com', 'Chase Gerundiano  "Chase"', 'Hogan Smith Law', 265.0, 280),
    ('chaseg@simplesitecompany.com', 'chaseslugger1107@gmail.com', 'Chase Gerundiano  "Chase"', 'Hogan Smith Law', 265.0, 280),
    ('chelzyc@simple.biz', 'chelzyhavez@gmail.com', 'Chavez, Chelzy "Chelzy"', 'Hogan Smith Law', 355.0, 370),
    ('chet@simple.biz', 'theresatecson83@icloud.com', 'Tecson, Ma. Theresa "Che"', 'Hogan Smith Law', 265.0, 280),
    ('choloh@simple.biz', 'cholohernandez69@gmail.com', 'Hernandez, Cholo "Cholo"', 'Hogan Smith Law', 265.0, 280),
    ('chrise@simple.biz', 'Chrischanenriquezj1@gmail.com', 'Enriquez, Chris Chan "Chris"', 'Hogan Smith Law', 305.0, 320),
    ('chrism@simple.biz', 'Christianbarker69@gmail.com', 'Mamhot, Niño Christian A. "Chris"', 'Hogan Smith Law', 305.0, 320),
    ('christiannr@simple.biz', 'roachrist02@gmail.com', 'Roa, Christian "Chris"', 'Hogan Smith Law', 265.0, 280),
    ('cindyg@simple.biz', 'cindygonzales2198@gmail.com', 'Gonzales, Cindy "Cindy"', 'Hogan Smith Law', 265.0, 280),
    ('cjc@simple.biz', 'ceejeicortes.731@gmail.com', 'Cortes, Cee Jei "CJ"', 'Hogan Smith Law', 265.0, 280),
    ('clarizr@simple.biz', 'clarizamaerosales@gmail.com', 'Rosales, Clariza Mae  "Clariz"', 'Hogan Smith Law', 235.0, 250),
    ('claudep@simple.biz', 'aldinebernz17@gmail.com', 'Punay, Claudine A "Claude"', 'Hogan Smith Law', 265.0, 280),
    ('cliffl@simple.biz', 'lopez.cliffroven@gmail.com', 'Lopez, Cliff Roven "Cliff''', 'Hogan Smith Law', 305.0, 320),
    ('cliffl@simplesitecompany.com', 'lopez.cliffroven@gmail.com', 'Lopez, Cliff Roven "Cliff''', 'Hogan Smith Law', 305.0, 320),
    ('clydem@simple.biz', 'c.mangawang1102@gmail.com', 'Mangawang, Clyde "Clyde"', 'Hogan Smith Law', 265.0, 280),
    ('crisc@simple.biz', 'ma.crismae25@gmail.com', 'Cañete, Ma. Cris Mae "Cris"', 'Hogan Smith Law', 235.0, 250),
    ('dales@simple.biz', 'daledelossantos.vahouse@gmail.com', 'Delos Santos, Dale "Dale"', 'Hogan Smith Law', 305.0, 320),
    ('dana@simple.biz', 'dan.abadjr@gmail.com', 'Abad, Danilo Jr "Dan"', 'Hogan Smith Law', 355.0, 370),
    ('dancp@simple.biz', 'dcpagha22@outlook.com', 'Pagharion, Dan Carlo "Dan"', 'Hogan Smith Law', 305.0, 320),
    ('danm@simple.biz', 'masacoted@gmail.com', 'Masacote, Dan Kristoffer "Dan"', 'Hogan Smith Law', 265.0, 280),
    ('daver@simple.biz', 'jdretis@gmail.com', 'Retis, John David  "Dave"', 'Hogan Smith Law', 265.0, 280),
    ('dextert@simple.biz', 'rdextertag@yahoo.com', 'Tagulinao, Ryan Dexter "Dexter"', 'Hogan Smith Law', 265.0, 280),
    ('donb@simple.biz', 'brandonedwardbillones@gmail.com', 'Billones, Brandon "Don"', 'Hogan Smith Law', 265.0, 280),
    ('dond@simple.biz', 'doness.dnss@gmail.com', 'Danosos, Doness Taboada "Don"', 'Hogan Smith Law', 325.0, 340),
    ('ede@simple.biz', 'edric.a.espiritu@gmail.com', 'Espiritu, Edric "Ed"', 'Hogan Smith Law', 265.0, 280),
    ('edi@simple.biz', 'eddieboyinfante14@gmail.com', 'Infante, Eddie "ED"', 'Hogan Smith Law', 225.0, 240),
    ('edm@simple.biz', 'Edrownjohn@gmail.com', 'Mabaga, Edrown John "ED"', 'Hogan Smith Law', 265.0, 280),
    ('edryckm@simple.biz', 'edryck212121@gmail.com', 'Mira, Edryck Mae N "Ed"', 'Hogan Smith Law', 265.0, 280),
    ('edzg@simple.biz', 'edlainegarcia03@gmail.com', 'Garcia, Edlaine "Edz"', 'Hogan Smith Law', 355.0, 370),
    ('ejm@simple.biz', 'Melchor00yahoo.com@gmail.com', 'Melchor, Ej "EJ"', 'Hogan Smith Law', 225.0, 240),
    ('elaizaha@simple.biz', 'elaizahjean9@gmail.com', 'Alcanzo, Elaizah Jean " Elaizah"', 'Hogan Smith Law', 265.0, 280),
    ('elaz@simple.biz', 'dionelazaspa@gmail.com', 'Zaspa, Dionela Rose "Nela"', 'Hogan Smith Law', 265.0, 280),
    ('elmob@simple.biz', 'elmerbiol.work@gmail.com', 'Biol, Elmer "Elmo"', 'Hogan Smith Law', 305.0, 320),
    ('emill@simple.biz', 'deleon1984emil@gmail.com', 'De Leon, Emiliano "Emil"', 'Hogan Smith Law', 265.0, 280),
    ('emmanuelf@simple.biz', 'frivaldoemmanuel@gmail.com', 'Frivaldo, Emmanuel John "Emmanuel"', 'Hogan Smith Law', 225.0, 240),
    ('emss@simple.biz', 'emilyburgossolon@gmail.com', 'Solon, Emily "Ems"', 'Hogan Smith Law', 425.0, 440),
    ('erict@simple.biz', 'ericsonteano0125@gmail.com', 'Teano, Ericson "Eric"', 'Hogan Smith Law', 265.0, 280),
    ('erjiee@simple.biz', 'erjieestolonio123@gmail.com', 'Estolonio, Erjie "Erjie"', 'Hogan Smith Law', 265.0, 280),
    ('eulap@simple.biz', 'eulajanepacheco@gmail.com', 'Pacheco, Eula Jane J.', 'Hogan Smith Law', 425.0, 440),
    ('ferdieb@simple.biz', 'ferdinandbondoc0223@gmail.com', 'Bondoc, Ferdinand "Ferdie"', 'Hogan Smith Law', 235.0, 250),
    ('field@simple.biz', 'fieldeguito19@gmail.com', 'Deguito, Fiel "Fiel"', 'Hogan Smith Law', 265.0, 280),
    ('francem@simple.biz', 'Franz.magallon17@gmail.com', 'Magallon, Francis "France"', 'Hogan Smith Law', 235.0, 250),
    ('francisf@simple.biz', 'francisjay621@gmail.com', 'Boybanting, Francis Jay "Francis"', 'Hogan Smith Law', 235.0, 250),
    ('franzs@simple.biz', 'ryder2332@gmail.com', 'Sancio, Franz Vincent  "Franz"', 'Hogan Smith Law', 225.0, 240),
    ('fredi@simple.biz', 'iansevilla1@gmail.com', 'Sevilla III, Seigfredo "Fred"', 'Hogan Smith Law', 265.0, 280),
    ('geloa@simple.biz', 'abuelpaulangelo@gmail.com', 'Abuel, Paul Angelo R "Gelo"', 'Hogan Smith Law', 265.0, 280),
    ('gelp@simple.biz', 'pgellierose@gmail.com', 'Paltao, Gellie Rose "Gel"', 'Hogan Smith Law', 225.0, 240),
    ('gelp@simplesitecompany.com', 'pgellierose@gmail.com', 'Paltao, Gellie Rose "Gel"', 'Hogan Smith Law', 225.0, 240),
    ('genep@simple.biz', 'geneabpasay@gmail.com', 'Pasay, Gene Alphonse "Gene"', 'Hogan Smith Law', 235.0, 250),
    ('gleng@simple.biz', 'glenngo2019@gmail.com', 'Go, Glenda "Glen"', 'Hogan Smith Law', 265.0, 280),
    ('grahama@simple.biz', 'grahamalolod19@gmail.com', 'Alolod, Graham Christopher P. "Graham"', 'Hogan Smith Law', 265.0, 280),
    ('guiaq@simple.biz', 'guiamariequillosa@gmail.com', 'Quillosa, Guia Maria Mercado "Guia"', 'Hogan Smith Law', 265.0, 280),
    ('guiaq@simplesitecompany.com', 'guiamariequillosa@gmail.com', 'Quillosa, Guia Maria Mercado "Guia"', 'Hogan Smith Law', 265.0, 280),
    ('gyd@simple.biz', 'gydmonsantotura21@gmail.com', 'Tura, Gyd', 'Hogan Smith Law', 500.0, 515),
    ('hannaa@simple.biz', 'hannahlynnabad@gmail.com', 'Abad, Hannah Lynn "Hannah"', 'Hogan Smith Law', 265.0, 280),
    ('hannan@simple.biz', 'misaremae@gmail.com', 'Nacional, Hanna Mae "Hanna"', 'Hogan Smith Law', 265.0, 280),
    ('hannesm@simple.biz', 'hannesmendez@gmail.com', 'Mendez, Hannes "Hannes"', 'Hogan Smith Law', 355.0, 370),
    ('hendryp@simple.biz', 'hpamatian@gmail.com', 'Pamatian, Hendry "Hendry"', 'Hogan Smith Law', 305.0, 320),
    ('inchetm@simple.biz', 'mavictoriamarasigan02@gmail.com', 'Marasigan, Ma. Victoria "Inchet"', 'Hogan Smith Law', 265.0, 280),
    ('ireneh@simple.biz', 'ireneruth.hernandez17@gmail.com', 'Hernandez, Ma. Irene Ruth "Irene"', 'Hogan Smith Law', 235.0, 250),
    ('irisb@simple.biz', 'imborgonia@gmail.com', 'Borgonia, Iris M.', 'Hogan Smith Law', 355.0, 370),
    ('isaact@simple.biz', 'cnsstncy1996@gmail.com', 'Tesalona, Isaac John "Isaac"', 'Hogan Smith Law', 305.0, 320),
    ('ivy@simple.biz', 'ivylee1391@gmail.com', 'Antig, Ivy Marie', 'Hogan Smith Law', 305.0, 320),
    ('ivym@simple.biz', 'ivylee1391@gmail.com', 'Antig, Ivy Marie', 'Hogan Smith Law', 305.0, 320),
    ('jakej@simple.biz', 'jacobjohnjackson@outlook.com', 'Jackson, Jacob John "Jake"', 'Hogan Smith Law', 355.0, 370),
    ('jaket@simple.biz', 'johnben080922@gmail.com', 'Tapere, John Benedict "Jake"', 'Hogan Smith Law', 265.0, 280),
    ('jamg@simple.biz', 'jamguanzon24@gmail.com', 'Guanzon, Jamaica P. "Jam"', 'Hogan Smith Law', 265.0, 280),
    ('jammers@simple.biz', 'jammersolijon@gmail.com', 'Solijon, Jammer  "Jam"', 'Hogan Smith Law', 265.0, 280),
    ('janinec@simple.biz', 'moisesjaninebolo@gmail.com', 'Certeza, Janine M "Janine"', 'Hogan Smith Law', 305.0, 320),
    ('jannj@simple.biz', 'jannandreijumonong@gmail.com', 'Jumonong, Jann Andrei "Jann"', 'Hogan Smith Law', 305.0, 320),
    ('janp@simple.biz', 'delpradovjan08@gmail.com', 'Del Prado, V-Jan  "Jan"', 'Hogan Smith Law', 265.0, 280),
    ('jaya@simple.biz', 'jayson.aguadonov291990@gmail.com', 'Aguado, Jayson "Jay"', 'Hogan Smith Law', 355.0, 370),
    ('jaya@simplesitecompany.com', 'jayson.aguadonov291990@gmail.com', 'Aguado, Jayson "Jay"', 'Hogan Smith Law', 355.0, 370),
    ('jayh@simple.biz', 'jmhernandez017@yahoo.com', 'Hernandez, John Michael', 'Hogan Smith Law', 225.0, 240),
    ('jaysond@simple.biz', 'daoayanjay360@gmail.com', 'Dao-ayan, Jayson O.  "Jayson"', 'Hogan Smith Law', 265.0, 280),
    ('jayveea@simple.biz', 'jvaliser@gmail.com', 'Aliser, Jayvee Lloyd "Jayvee"', 'Hogan Smith Law', 225.0, 240),
    ('jaywlc@simple.biz', 'markjaywlcabatingan@gmail.com', 'Cabatingan, Mark Jaywl "Mark"', 'Hogan Smith Law', 225.0, 240),
    ('jazminer@simple.biz', 'jasmineroa10@gmail.com', 'Roa, Sajda "Jazmine"', 'Hogan Smith Law', 355.0, 370),
    ('jazzr@simple.biz', 'haileybriana23@gmail.com', 'Redulla, Jazz Javier', 'Hogan Smith Law', 425.0, 440),
    ('jcp@simple.biz', 'eliangjohn09@gmail.com', 'Pascual, John Christopher "JC"', 'Hogan Smith Law', 265.0, 280),
    ('jdd@simple.biz', 'dagatanjensen708@gmail.com', 'Dagatan, Jensen "JD"', 'Hogan Smith Law', 265.0, 280),
    ('jeant@simple.biz', 'hontupzy31@gmail.com', 'Tupas, Honey Jean "Jean"', 'Hogan Smith Law', 355.0, 370),
    ('jebr@simple.biz', 'jebpatrickravanilla@gmail.com', 'Ravanilla, Jeb Patrick  "Jeb"', 'Hogan Smith Law', 305.0, 320),
    ('jedp@simple.biz', 'jed4gellie1991@gmail.com', 'Porquez Jeremy Jed "Jed"', 'Hogan Smith Law', 265.0, 280),
    ('jehdb@simple.biz', 'monjehdbasman@gmail.com', 'Basman,Jehd Monsour "Jhed"', 'Hogan Smith Law', 355.0, 370),
    ('jemt@simple.biz', 'jeremytanajora@gmail.com', 'Tañajora, Jeremy "Jem"', 'Hogan Smith Law', 355.0, 370),
    ('jemv@simple.biz', 'jempoako1@gmail.com', 'Vasquez, Jeremy "Jem"', 'Hogan Smith Law', 265.0, 280),
    ('jenessap@simple.biz', 'jenessaparaiso85@gmail.com', 'Paraiso, Janessa "Jen"', 'Hogan Smith Law', 235.0, 250),
    ('jeni@simple.biz', 'lyniejanecantonjos@gmail.com', 'Ipili, Lynie Jane "Jen"', 'Hogan Smith Law', 225.0, 240),
    ('jenl@simple.biz', 'barbazajennifer05@gmail.com', 'Lagos, Jennifer "Jen"', 'Hogan Smith Law', 305.0, 320),
    ('jeoa@simple.biz', 'jeofryagbo@gmail.com', 'Agbo, Jeofry Kim "Jeo"', 'Hogan Smith Law', 355.0, 370),
    ('jeriemym@simple.biz', 'jeriemy.adove@gmail.com', 'Adove, Jeriemy Mckinly "Jeriemy"', 'Hogan Smith Law', 265.0, 280),
    ('jeromea@simple.biz', 'jeromeaguirre90@gmail.com', 'Aguirre, Jerome G "Jerome"', 'Hogan Smith Law', 355.0, 370),
    ('jerrekl@simple.biz', 'jerreklim@gmail.com', 'Lim, Jerrek Anthony', 'Hogan Smith Law', 265.0, 280),
    ('jerryl@simple.biz', 'jerelee.lucero1@yahoo.com', 'Langcuyan, Jerelee "Jerry"', 'Hogan Smith Law', 265.0, 280),
    ('jetg@simple.biz', 'jetgalino29@gmail.com', 'Galino, Jet "Jet"', 'Hogan Smith Law', 305.0, 320),
    ('jigsj@simple.biz', 'juganrandy@gmail.com', 'Jugan, Randy John "Jigs"', 'Hogan Smith Law', 225.0, 240),
    ('jimb@simple.biz', 'clarkboongaling@gmail.com', 'Boongaling, Gim Clark "Jim"', 'Hogan Smith Law', 265.0, 280),
    ('jms@simple.biz', 'johnboking13@gmail.com', 'Sarana, John Michael R "JM"', 'Hogan Smith Law', 265.0, 280),
    ('johannas@simple.biz', 'summersacedon@gmail.com', 'Sacedon, Johanna Grace "Johanna"', 'Hogan Smith Law', 305.0, 320),
    ('johannas@simplesitecompany.com', 'johanna.sarmiento507@gmail.com', 'Sacedon, Johanna Grace "Johanna"', 'Hogan Smith Law', 305.0, 320),
    ('johnbv@simple.biz', 'johnbvillanueva1@gmail.com', 'Villanueva, John B "John"', 'Hogan Smith Law', 285.0, 300),
    ('johnl@simple.biz', 'lagosjohnmichael@gmail.com', 'Lagos, John Michael "John"', 'Hogan Smith Law', 305.0, 320),
    ('johnq@simple.biz', 'johnrhiel7querijero@gmail.com', 'Querijero, John Rhiel "John"', 'Hogan Smith Law', 265.0, 280),
    ('johnwp@simple.biz', 'iamjohnwestley@outlook.com', 'Paule, John Westley "Westley"', 'Hogan Smith Law', 355.0, 370),
    ('joloe@simple.biz', 'joloesguerra50@gmail.com', 'Esguerra, Jolo Miguel "Jolo"', 'Hogan Smith Law', 305.0, 320),
    ('jomsa@simple.biz', 'jomarlegaspiarce@gmail.com', 'Arce, Jomar "Jom"', 'Hogan Smith Law', 265.0, 280),
    ('jonj@simple.biz', 'jonfjaring@gmail.com', 'Jaring, Jon Francis "Jon"', 'Hogan Smith Law', 265.0, 280),
    ('josephf@simple.biz', 'jaaflorita@gmail.com', 'Florita, Joseph Anthony "Joseph"', 'Hogan Smith Law', 265.0, 280),
    ('josephinet@simple.biz', 'jorichojhames@gmail.com', 'Torralba, Josephine', 'Hogan Smith Law', 305.0, 320),
    ('josephr@simple.biz', 'sephlian19@gmail.com', 'Robles, Joseph "Joseph"', 'Hogan Smith Law', 305.0, 320),
    ('josha@simple.biz', 'joshua098989@gmail.com', 'Aquino, Joshua Jake "Josh"', 'Hogan Smith Law', 235.0, 250),
    ('josied@simple.biz', 'josephinedoon@gmail.com', 'Doon, Josephine "Josie"', 'Hogan Smith Law', 265.0, 280),
    ('joy@hogansmith.com', 'Baldonebrojj@gmail.com', 'Baldonebro, Joycel "Joy"', 'Hogan Smith Law', 305.0, 320),
    ('joyb@simple.biz', 'Baldonebrojj@gmail.com', 'Baldonebro, Joycel "Joy"', 'Hogan Smith Law', 305.0, 320),
    ('jpb@simple.biz', 'bacallanjohnpaul@gmail.com', 'Bacallan , John Paul "JP"', 'Hogan Smith Law', 305.0, 320),
    ('judyannc@simple.biz', 'judyanncanalesdausan@gmail.com', 'Canales,Judy Ann  "Judy"', 'Hogan Smith Law', 235.0, 250),
    ('judyannc@simplesitecompany.com', 'judyanncanalesdausan@gmail.com', 'Canales,Judy Ann  "Judy"', 'Hogan Smith Law', 235.0, 250),
    ('juliane@simple.biz', 'julianelevazo977@gmail.com', 'Elevazo, Julian "Julian"', 'Hogan Smith Law', 305.0, 320),
    ('juliec@simple.biz', 'credojulieann0@gmail.com', 'Credo, Julie Ann "Julie"', 'Hogan Smith Law', 355.0, 370),
    ('justineb@simple.biz', 'zymerzolo@gmail.com', 'Buenvenida, Bong Justine "Justine"', 'Hogan Smith Law', 225.0, 240),
    ('kailab@simple.biz', 'mechailabenito10@gmail.com', 'Benito, Mechaila "Kaila"', 'Hogan Smith Law', 265.0, 280),
    ('karln@simple.biz', 'karllouienoynay@gmail.com', 'Noynay, Karl Louie "Karl"', 'Hogan Smith Law', 235.0, 250),
    ('karmina@simple.biz', 'minadulu@gmail.com', 'Dulu, Maria Karmina "Mina"', 'Hogan Smith Law', 305.0, 320),
    ('kated@simple.biz', 'catlinerosedanao@gmail.com', 'Danao, Catline Rose "Kate"', 'Hogan Smith Law', 235.0, 250),
    ('katet@simple.biz', 'rencelkhate@gmail.com', 'Tugna, Rencel Khate "Kate"', 'Hogan Smith Law', 225.0, 240),
    ('kathl@simple.biz', 'klapure23@gmail.com', 'Lapure, Kathleen "Kath"', 'Hogan Smith Law', 305.0, 320),
    ('kathl@simplesitecompany.com', 'klapure23@gmail.com', 'Lapure, Kathleen "Kath"', 'Hogan Smith Law', 305.0, 320),
    ('kayea@simple.biz', 'kayeagustin779@gmail.com', 'Agustin, Kaye Lanie Munoz', 'Hogan Smith Law', 305.0, 320),
    ('keithc@simple.biz', 'Keith.cayosa@gmail.com', 'Cayosa, Keith Xavier Jonathan"Keith"', 'Hogan Smith Law', 305.0, 320),
    ('kellyc@simple.biz', 'mkelc031599@gmail.com', 'Canave, Melisa Kelly "Kelly"', 'Hogan Smith Law', 305.0, 320),
    ('kennm@simple.biz', 'kenneth.melliza03@gmail.com', 'Melliza, Kenneth "Ken"', 'Hogan Smith Law', 265.0, 280),
    ('kevinu@simple.biz', 'kevinkarluy@yahoo.com', 'Uy, Kevin Karl "Kevin"', 'Hogan Smith Law', 235.0, 250),
    ('khrism@simple.biz', 'khrisna.moises@gmail.com', 'Moises, Khrisna "Khris"', 'Hogan Smith Law', 305.0, 320),
    ('kimbr@simple.biz', 'kbriones0924@gmail.com', 'Briones, Kim "Kim"', 'Hogan Smith Law', 265.0, 280),
    ('kimr@simple.biz', 'kimroxas323@gmail.com', 'Roxas, Kim Augusteine "Kim"', 'Hogan Smith Law', 265.0, 280),
    ('kristinec@simple.biz', 'gaileyz_08@yahoo.com', 'Labo, Kristine Abigail "Kristine"', 'Hogan Smith Law', 325.0, 340),
    ('kryzeln@simple.biz', 'navarosakryzel@gmail.com', 'Navarosa, Kryzel "Kryzel"', 'Hogan Smith Law', 285.0, 300),
    ('ktelc@simple.biz', 'kristeljcatuday04@gmail.com', 'Catuday, Kristel Joy "Ktel"', 'Hogan Smith Law', 235.0, 250),
    ('kyrag@simple.biz', 'chiee.galicia@gmail.com', 'Galicia, Kyra Archie " Kyra"', 'Hogan Smith Law', 225.0, 240),
    ('lanf@simple.biz', 'lanoyfuertes@gmail.com', 'Fuertes, Lani', 'Hogan Smith Law', 355.0, 370),
    ('lauricej@simple.biz', 'dc.lm.caudor@gmail.com', 'Justiniane, Laurice Monette C "Laurice"', 'Hogan Smith Law', 225.0, 240),
    ('lawrenced@simple.biz', 'lawrencebearfccyiloilo@gmail.com', 'David, Lawrence Francis "Lawrence"', 'Hogan Smith Law', 305.0, 320),
    ('leighl@simple.biz', 'belderolleigh@gmail.com', 'Lawa, Leigh "Leigh"', 'Hogan Smith Law', 225.0, 240),
    ('liccac@simple.biz', 'noreenliccacastillo@gmail.com', 'Castillo, Noreen Licca "Licca"', 'Hogan Smith Law', 225.0, 240),
    ('liefe@simple.biz', 'liefdenriquez@gmail.com', 'Enriquez, Lief Lester "Leif"', 'Hogan Smith Law', 305.0, 320),
    ('lincolnm@simple.biz', 'lincolneman689@gmail.com', 'Moguies, Lincoln Eman', 'Hogan Smith Law', 225.0, 240),
    ('linkm@simple.biz', 'gerard.linc@gmail.com', 'Mamaril, Lincoln Gerard A "Link"', 'Hogan Smith Law', 305.0, 320),
    ('lorar@simple.biz', 'eloradawnr@gmail.com', 'Roflo, Elora Dawn Del Mundo "Lora"', 'Hogan Smith Law', 355.0, 370),
    ('loriem@simple.biz', 'lsanmateo07@gmail.com', 'San Mateo, Lorie Ann "Lorie"', 'Hogan Smith Law', 265.0, 280),
    ('lovelyc@simple.biz', 'lovelycelis13@gmail.com', 'Celis, Lovely V "Love"', 'Hogan Smith Law', 265.0, 280),
    ('luisd@simple.biz', 'patrick.webganic@gmail.com', 'Damasco, Luis "Luis"', 'Hogan Smith Law', 225.0, 240),
    ('luisd@simplesitecompany.com', 'patrick.webganic@gmail.com', 'Damasco, Luis "Luis"', 'Hogan Smith Law', 225.0, 240),
    ('lynj@simple.biz', 'caparida.voiceville@gmail.com', 'Johnson, Shielalyn "Lyn"', 'Hogan Smith Law', 325.0, 340),
    ('lynnb@simple.biz', 'javierpetalyn@gmail.com', 'Binas, Petalyn "Lynn"', 'Hogan Smith Law', 305.0, 320),
    ('mackp@simple.biz', 'josephmichaelplugio@gmail.com', 'Joseph Michael Plugio "Mack"', 'Hogan Smith Law', 305.0, 320),
    ('mackyj@simple.biz', 'reymarkj.jordan@gmail.com', 'Jordan, Reymark Japon "Macky"', 'Hogan Smith Law', 265.0, 280),
    ('macp@simple.biz', 'treintaycuatromack@gmail.com', 'Pahunang Mark Anthony L. "Mac"-', 'Hogan Smith Law', 305.0, 320),
    ('maddies@simple.biz', 'sabadomadi@gmail.com', 'Sabado, Madison Lori L "Maddie"', 'Hogan Smith Law', 265.0, 280),
    ('marbieb@simple.biz', 'Imphreeta0610@gmail.com', 'Buat, Janmarie Bernadette Ocampo "Marbie"', 'Hogan Smith Law', 235.0, 250),
    ('marcusu@simple.biz', 'marcusumpad05@gmail.com', 'Umpad, Marcus "Marcus"', 'Hogan Smith Law', 225.0, 240),
    ('mariam@simple.biz', 'maria.magallano26@gmail.com', 'Magallano, Maria Corazon "Maria"', 'Hogan Smith Law', 265.0, 280),
    ('maricard@simple.biz', 'maricar.v.docallos@gmail.com', 'Docallos, Maricar "Maricar"', 'Hogan Smith Law', 265.0, 280),
    ('maricorc@simple.biz', 'lorenzomaricor@gmail.com', 'Cruz, Maricor Lorenzo "Marie"', 'Hogan Smith Law', 265.0, 280),
    ('marie@simple.biz', 'catherinecalugay235@gmail.com', 'Calugay, Catherine Marie "Marie"', 'Hogan Smith Law', 305.0, 320),
    ('mariea@simple.biz', 'tonifulleros0412@gmail.com', 'Fulleros, Marie Antonette "Marie"', 'Hogan Smith Law', 265.0, 280),
    ('mariec@simple.biz', 'catherinecalugay235@gmail.com', 'Calugay, Catherine Marie "Marie"', 'Hogan Smith Law', 305.0, 320),
    ('mariely@simple.biz', 'yungcomarielace99@gmail.com', 'Yungco, Marielace Buena Fe "Mariel"', 'Hogan Smith Law', 425.0, 440),
    ('mariettac@simple.biz', 'candormarietta@gmail.com', 'Candor, Marietta "May"', 'Hogan Smith Law', 265.0, 280),
    ('marjf@simple.biz', 'marjoriefernandez245@gmail.com', 'Fernandez, Marjorie "Marj"', 'Hogan Smith Law', 265.0, 280),
    ('marjunm@simple.biz', 'marjunmacamay7@gmail.com', 'Macamay, Marjun "Marjun"', 'Hogan Smith Law', 265.0, 280),
    ('markd@simple.biz', 'kram0147892@gmail.com', 'Descalzo, Mark Vincent "Mark"', 'Hogan Smith Law', 265.0, 280),
    ('markmo@simple.biz', 'mark.molarteworks@gmail.com', 'Molarte, Mark', 'Hogan Smith Law', 225.0, 240),
    ('mats@simple.biz', 'bishopsalas27@gmail.com', 'Salas, Mathew King "Mat"', 'Hogan Smith Law', 235.0, 250),
    ('mayi@simple.biz', 'maybelleinggo@gmail.com', 'Inggo, Maybelle "May"', 'Hogan Smith Law', 305.0, 320),
    ('mayt@simple.biz', 'maetampos4@gmail.com', 'Tampos, Mae "May"', 'Hogan Smith Law', 265.0, 280),
    ('melchezedeks@simple.biz', 'melchezedek22@gmail.com', 'Sumandang, Melchezedek "Mel"', 'Hogan Smith Law', 265.0, 280),
    ('melm@simple.biz', 'megadeth980@gmail.com', 'Manalo, Armel D. "Mel"', 'Hogan Smith Law', 235.0, 250),
    ('melvsf@simple.biz', 'melvsfaeldan@gmail.com', 'Faeldan, Melvin "Melvs"', 'Hogan Smith Law', 265.0, 280),
    ('mgm@simple.biz', 'mgmparero@gmail.com', 'Manalo, Mary Grace "MG"', 'Hogan Smith Law', 235.0, 250),
    ('miahl@simple.biz', 'nleosala@gmail.com', 'Leosala , Nehemiah "Miah"', 'Hogan Smith Law', 265.0, 280),
    ('miaj@simple.biz', 'Mbenedictos2018@gmail.com', 'Benedictos, Miarela Javier "Mia"', 'Hogan Smith Law', 305.0, 320),
    ('michaelb@simple.biz', 'mrbacalla@gmail.com', 'Bacalla, Michael Ryan "Mike"', 'Hogan Smith Law', 225.0, 240),
    ('mickyr@simple.biz', 'mics.jenelyn@gmail.com', 'Reynante, Micky Jenelyn A "Micky"', 'Hogan Smith Law', 265.0, 280),
    ('migsl@simple.biz', 'miguel.locmayon1@gmail.com', 'Locmayon, Miguel "Migs"', 'Hogan Smith Law', 225.0, 240),
    ('migsl@simplesitecompany.com', 'miguel.locmayon1@gmail.com', 'Locmayon, Miguel "Migs"', 'Hogan Smith Law', 225.0, 240),
    ('mikeb@simple.biz', 'checkmike16@gmail.com', 'Baillo, Jan Michael M "Mike"', 'Hogan Smith Law', 265.0, 280),
    ('mikekja@simple.biz', 'mike.agtag@gmail.com', 'Agtag, Mike King Jay Erano "Mike"', 'Hogan Smith Law', 305.0, 320),
    ('mikep@simple.biz', 'placiamichaels@yahoo.com', 'Placia, Michael S "Mike"', 'Hogan Smith Law', 305.0, 320),
    ('miket@simple.biz', 'mikelltorres08@gmail.com', 'Torres, Michael John "Mike"', 'Hogan Smith Law', 305.0, 320),
    ('mina@simple.biz', 'minadulu@gmail.com', 'Dulu, Maria Karmina "Mina"', 'Hogan Smith Law', 305.0, 320),
    ('minad@simple.biz', 'minadulu@gmail.com', 'Dulu, Maria Karmina "Mina"', 'Hogan Smith Law', 305.0, 320),
    ('mitsa@simple.biz', 'mitsumeaguilar@gmail.com', 'Aguilar Mitsume "Mits"', 'Hogan Smith Law', 225.0, 240),
    ('nadinec@simple.biz', 'nadinejoychavez15@gmail.com', 'Chavez, Nadine', 'Hogan Smith Law', 305.0, 320),
    ('natel@simple.biz', 'natelunar@gmail.com', 'Lunar, Jonathan "Nate"', 'Hogan Smith Law', 355.0, 370),
    ('neliab@simple.biz', 'neliasabal2@gmail.com', 'Boiser, Nelia "Nelia"', 'Hogan Smith Law', 265.0, 280),
    ('nesm@simple.biz', 'nessanmacajelos01@icloud.com', 'Macajelos, Nessan "Nes"', 'Hogan Smith Law', 265.0, 280),
    ('nesm@simplesitecompany.com', 'nessanmacajelos01@icloud.com', 'Macajelos, Nessan "Nes"', 'Hogan Smith Law', 355.0, 370),
    ('nete@simple.biz', 'cebardo21@gmail.com', 'Ebardo, Carol "Net"', 'Hogan Smith Law', 285.0, 300),
    ('nics@simple.biz', 'sornito.nic@gmail.com', 'Sornito, Nicole "Nic"', 'Hogan Smith Law', 355.0, 370),
    ('nikaa@simple.biz', 'nikaaldohueza123@gmail.com', 'Aldohueza Nika Alexis "Nika"', 'Hogan Smith Law', 235.0, 250),
    ('ninac@simple.biz', 'nhinapotz15@gmail.com', 'Cruz, Nina Christina "Nina"', 'Hogan Smith Law', 285.0, 300),
    ('noelm@simple.biz', 'noel.manlulu28@gmail.com', 'Manlulu, Noel "Noel"', 'Hogan Smith Law', 235.0, 250),
    ('noimeg@simple.biz', 'noime.gaspar15@gmail.com', 'Gaspar, Noime "Noime"', 'Hogan Smith Law', 285.0, 300),
    ('norwinb@simple.biz', 'spikee21@gmail.com', 'Binas, Norwin "Norwin"', 'Hogan Smith Law', 355.0, 370),
    ('olie@simple.biz', 'olimarxrestanislao@gmail.com', 'Estanislao, Olimar Ramos "Oli""', 'Hogan Smith Law', 305.0, 320),
    ('patv@simple.biz', 'patriciamikaelav@gmail.com', 'Velasco, Patricia Mikaela "Pat"', 'Hogan Smith Law', 305.0, 320),
    ('queenb@simple.biz', 'queenciseve@gmail.com', 'Baguio, Queencis Eve "Queen"', 'Hogan Smith Law', 305.0, 320),
    ('rachelc@simple.biz', 'ybio.rachelamor@gmail.com', 'Cagape, Rachel Amor "Rachel"', 'Hogan Smith Law', 225.0, 240),
    ('rafa@simple.biz', 'rafael.angelo.andres@gmail.com', 'Andres, Rafael Angelo "Raf"', 'Hogan Smith Law', 235.0, 250),
    ('rainp@simple.biz', 'reynanp.lmedia@gmail.com', 'Postrano, Reynan "Rain"', 'Hogan Smith Law', 225.0, 240),
    ('ralfp@simple.biz', 'josephralf.pamintuan@gmail.com', 'Pamintuan, Joseph Ralf "Joe"', 'Hogan Smith Law', 265.0, 280),
    ('ralphr@simple.biz', 'princeralph1437@gmail.com', 'Ramirez, Ralph William "Ralph"', 'Hogan Smith Law', 265.0, 280),
    ('raphs@simple.biz', 'raphaelsepnio30@gmail.com', 'Sepnio, Raphael "Raph"', 'Hogan Smith Law', 235.0, 250),
    ('rayc@simple.biz', 'jhonrheyconejos@gmail.com', 'Conejos, Jhon Rhey "Ray"', 'Hogan Smith Law', 305.0, 320),
    ('rayc@simplesitecompany.com', 'jhonrheyconejos@gmail.com', 'Conejos, Jhon Rhey "Ray"', 'Hogan Smith Law', 305.0, 320),
    ('reeds@simple.biz', 'reedjensensalvador17@gmail.com', 'Salvador, Reed Jensen "Reed"', 'Hogan Smith Law', 265.0, 280),
    ('reinal@simple.biz', 'reina.pepito@gmail.com', 'Lawas, Reina', 'Hogan Smith Law', 225.0, 240),
    ('renards@simple.biz', 'renardseledio24@gmail.com', 'Seledio, Renard "Renard"', 'Hogan Smith Law', 235.0, 250),
    ('rend@simple.biz', 'stodomingomariren@gmail.com', 'Sto Domingo, Mariren "Ren"', 'Hogan Smith Law', 305.0, 320),
    ('richardm@simple.biz', 'manuyagrichardangelo@gmail.com', 'Manuyag, Richard Angelo "Richard"', 'Hogan Smith Law', 265.0, 280),
    ('robm@simple.biz', 'robertiimula@gmail.com', 'Mula, Robert "Rob"', 'Hogan Smith Law', 355.0, 370),
    ('robm@simplesitecompany.com', 'robertiimula@gmail.com', 'Mula, Robert "Rob"', 'Hogan Smith Law', 355.0, 370),
    ('robp@simple.biz', 'kenkenzpegorosa@gmail.com', 'Pegorosa, Bel Robert "Rob"', 'Hogan Smith Law', 235.0, 250),
    ('robt@simple.biz', 'robtantiado27@gmail.com', 'Tantiado,  Rob "Rob"', 'Hogan Smith Law', 265.0, 280),
    ('rochelled@simple.biz', 'Rochellegraced@gmail.com', 'Dumlao, Rochelle Grace "Rochelle"', 'Hogan Smith Law', 265.0, 280),
    ('rockym@simple.biz', 'jeddmacalinga@gmail.com', 'Macalinga, Rocky Jedd "Rocky"', 'Hogan Smith Law', 265.0, 280),
    ('roda@simple.biz', 'girodalejandre278@gmail.com', 'Alejandre, Girod "Rod"', 'Hogan Smith Law', 265.0, 280),
    ('rosed@simple.biz', 'joydente.121698@gmail.com', 'Dente, Rosemary Joy "Rose"', 'Hogan Smith Law', 305.0, 320),
    ('rosep@simple.biz', 'lhenvillaruel.lv@gmail.com', 'Principe, Roses "Rose"', 'Hogan Smith Law', 265.0, 280),
    ('roses@simple.biz', 'rose.kyros1129@gmail.com', 'Sardan, Rosemarie Marquez "Rose"', 'Hogan Smith Law', 265.0, 280),
    ('ruffag@simple.biz', 'ruffa.diaz@yahoo.com', 'Gallego, Ruffa Mae "Ruffa"', 'Hogan Smith Law', 265.0, 280),
    ('ruffamaeg@simple.biz', 'heyyyruffag@gmail.com', 'Generalao, Ruffa Mae  "Ruffa"', 'Hogan Smith Law', 265.0, 280),
    ('russelm@simple.biz', 'rmmacabali23@gmail.com', 'Macabali, Russel "Russel"', 'Hogan Smith Law', 225.0, 240),
    ('ruswellb@simple.biz', 'rus1980bart@gmail.com', 'Bartolata, Ruswell  ""Ruswell"', 'Hogan Smith Law', 305.0, 320),
    ('rvr@simple.biz', '1925rvrivera@gmail.com', 'Rivera, Roy "RV"', 'Hogan Smith Law', 305.0, 320),
    ('ryej@simple.biz', 'ryanrigeldejesus@gmail.com', 'De Jesus, Ryan Rigel "Rye"', 'Hogan Smith Law', 225.0, 240),
    ('sarahf@simple.biz', 'itssarahjanef@gmail.com', 'Fantilagan, Sarah "Sarah "', 'Hogan Smith Law', 305.0, 320),
    ('sarahf@simplesitecompany.com', 'itssarahjanef@gmail.com', 'Fantilagan, Sarah "Sarah "', 'Hogan Smith Law', 305.0, 320),
    ('shaie@simple.biz', 'ariahsespiritu13@gmail.com', 'Espiritu, Shaira "Shai"', 'Hogan Smith Law', 235.0, 250),
    ('shairal@simple.biz', 'shairalyralaki@gmail.com', 'Laki, Shaira Lyra "Shaira"', 'Hogan Smith Law', 235.0, 250),
    ('shairal@simplesitecompany.com', 'shairalyralaki@gmail.com', 'Laki, Shaira Lyra "Shaira"', 'Hogan Smith Law', 235.0, 250),
    ('sherwin@simple.biz', 'sherwin.gsantos@gmail.com', 'Santos, Sherwin', 'Hogan Smith Law', 225.0, 240),
    ('sheryld@simple.biz', 'lyrehs_2@yahoo.com', 'Diano, Sheryl Aiza "Sheryl"', 'Hogan Smith Law', 265.0, 280),
    ('stara@simple.biz', 'esterlita.abella2023@gmail.com', 'Abella, Esterlita I. "Star"', 'Hogan Smith Law', 425.0, 440),
    ('stephc@simple.biz', 'canalesmarystiphanny@gmail.com', 'Canales, Mary Stiphanny "Steph"', 'Hogan Smith Law', 265.0, 280),
    ('stephc@simplesitecompany.com', 'canalesmarystiphanny@gmail.com', 'Canales, Mary Stiphanny "Steph"', 'Hogan Smith Law', 265.0, 280),
    ('syr@simple.biz', 'isabellerosal29@gmail.com', 'Rosal, Isabelle "Sy"', 'Hogan Smith Law', 265.0, 280),
    ('talat@simple.biz', 'cristaljoycetia@gmail.com', 'Tia, Cristal Joyce "Tala"', 'Hogan Smith Law', 225.0, 240),
    ('tinb@simple.biz', 'khristine.garcia2024@gmail.com', 'Bumagat, Khristine G. "Tin"', 'Hogan Smith Law', 265.0, 280),
    ('tinem@simple.biz', 'jmalazarte21@gmail.com', 'Malazarte, Justine Marie Evette "Tine"', 'Hogan Smith Law', 265.0, 280),
    ('tinz@simple.biz', 'riyaz.kiat@gmail.com', 'Zambra, Ma.Justine "Tin"', 'Hogan Smith Law', 235.0, 250),
    ('tinz@simplesitecompany.com', 'riyaz.kiat@gmail.com', 'Zambra, Ma.Justine "Tin"', 'Hogan Smith Law', 235.0, 250),
    ('tobic@simple.biz', 'tobicadag01@gmail.com', 'Cadag, Tobi "Tobi"', 'Hogan Smith Law', 305.0, 320),
    ('tonc@simple.biz', 'clintoncaceres111294@gmail.com', 'Caceres, Clinton "Ton"', 'Hogan Smith Law', 305.0, 320),
    ('tonrayc@simple.biz', 'tan.caldoza14@gmail.com', 'Caldoza,Tonray "Ray"', 'Hogan Smith Law', 265.0, 280),
    ('ulyg@simple.biz', 'ulyssesgalagnara316@gmail.com', 'Galagnara, Ulysses "Uly"', 'Hogan Smith Law', 265.0, 280),
    ('vanessac@simple.biz', 'vanessacultura92@gmail.com', 'Cultura, Vanessa "Vanessa"', 'Hogan Smith Law', 305.0, 320),
    ('vanessad@simple.biz', 'delvanmae@gmail.com', 'Delgado, Vanessa Mae', 'Hogan Smith Law', 265.0, 280),
    ('vanp@simple.biz', 'bandagpatigayon@gmail.com', 'Patigayon, Evander "Van"', 'Hogan Smith Law', 285.0, 300),
    ('veec@simple.biz', 'veronelamortos@gmail.com', 'Mortos, Veronela Clarissa "Vee"', 'Hogan Smith Law', 425.0, 440),
    ('verag@simple.biz', 'veraargylle@gmail.com', 'Giducos, Vera "Vera"', 'Hogan Smith Law', 305.0, 320),
    ('vinzm@simple.biz', 'vincedeath900@gmail.com', 'Medina, Vince Hubert "Vinz"', 'Hogan Smith Law', 265.0, 280),
    ('wilf@simple.biz', 'wferna012@gmail.com', 'Fernandez, Wilfredo Jr "Wil"', 'Hogan Smith Law', 355.0, 370),
    ('zaka@simple.biz', 'zakiaguell@ymail.com', 'Asackil, Aguell "Zak"', 'Hogan Smith Law', 265.0, 280),
    ('zyberb@simple.biz', 'bionedazyber@gmail.com', 'Bioneda, Zyber Jison "Zyber"', 'Hogan Smith Law', 265.0, 280)
),

-- 1) Insert into employee_hourly_rates where no row exists for this email
inserted_rates AS (
  INSERT INTO employee_hourly_rates ("Work Email", "Personal Email", "Department", "Regular Rate", "OT Rate")
  SELECT s.work_email, NULLIF(s.personal_email, ''), s.department, s.regular_rate::numeric, s.ot_rate::numeric
  FROM staging s
  WHERE NOT EXISTS (
    SELECT 1 FROM employee_hourly_rates r
    WHERE lower(trim(r."Work Email")) = s.work_email
  )
  RETURNING 1
),

-- 2) Fill blank Regular/OT on existing rows, per-column (numeric → IS NULL is the blank test)
updated_rates AS (
  UPDATE employee_hourly_rates r
  SET
    "Regular Rate" = COALESCE(r."Regular Rate", s.regular_rate::numeric),
    "OT Rate"     = COALESCE(r."OT Rate",     s.ot_rate::numeric)
  FROM staging s
  WHERE lower(trim(r."Work Email")) = s.work_email
    AND (r."Regular Rate" IS NULL OR r."OT Rate" IS NULL)
  RETURNING 1
),

-- 3) Insert into global_master_list where no row exists for this email
inserted_master AS (
  INSERT INTO global_master_list ("Name", "Department", "Work Email", "Personal Email")
  SELECT s.name, s.department, s.work_email, NULLIF(s.personal_email, '')
  FROM staging s
  WHERE NOT EXISTS (
    SELECT 1 FROM global_master_list m
    WHERE lower(trim(m."Work Email")) = s.work_email
  )
  RETURNING 1
)

SELECT
  (SELECT COUNT(*) FROM inserted_rates)   AS rates_rows_inserted,
  (SELECT COUNT(*) FROM updated_rates)    AS rates_rows_blank_filled,
  (SELECT COUNT(*) FROM inserted_master)  AS master_rows_inserted;
