-- Employee Support: an employee asks a question about their pay, hours or
-- records from inside /employee, and one of five named people answers it from
-- a new section on /tickets.
--
-- Approved by Carla 2026-09-15 (signed proposal). Plan:
-- docs/superpowers/plans/2026-09-14-employee-support.md
--
-- WHY THIS IS NOT A COLUMN ON public.tickets
-- ---------------------------------------------------------------------------
-- The HRIS-updates Kanban board's three tables were created with NO row-level
-- security and NO policy, and all three were added to the supabase_realtime
-- publication (references/sql/migrate/2026-07-15_tickets_kanban.sql:41-135).
-- Authorization for that board lives entirely in the route handlers, which is
-- survivable for "the drag-and-drop flickers on drop" and is not survivable for
-- "my manager is underpaying me". Everything filed here is HR-grade: pay
-- disputes, bank questions, and complaints naming a person. Putting it in a
-- table any anon-key holder can read is a new hole, not a reuse.
--
-- Two further blockers made the shared table impossible rather than merely
-- unwise: every ticket created by anyone but the board owner is force-assigned
-- to him (app/api/tickets/route.ts:91-93), so no support staffer could ever be
-- given one; and archive is creator-or-admin only, where the creator is an
-- employee who cannot reach the route at all, so only an admin could ever close
-- one.
--
-- THIS TABLE IS DELIBERATELY *NOT* ADDED TO supabase_realtime.
-- ---------------------------------------------------------------------------
-- Do not add it. postgres_changes is dead for the anon browser on any
-- RLS-guarded table (memory/supabase-realtime-anon-rls-dead), so making it
-- deliver would mean a permissive anon SELECT policy — precisely what must not
-- exist here. Both surfaces poll through gated routes instead. If a live signal
-- is ever wanted, broadcast the FACT that ticket N changed and let the client
-- re-fetch through the route; never put a message body on a public topic.

-- ===========================================================================
-- Tickets
-- ===========================================================================

create table if not exists public.employee_support_tickets (
  id            uuid primary key default gen_random_uuid(),

  -- The human-facing number, its OWN series. Deliberately not sharing the
  -- Kanban board's tickets.ticket_no: these are a different kind of object with
  -- a different lifecycle, and one series would interleave them so that
  -- "ticket 1043" is ambiguous between two boards.
  ticket_no     bigint generated by default as identity,

  -- Identity. `work_email` is the MASTER work email resolved server-side; it is
  -- the key every other surface joins on. `filed_by_email` is the address the
  -- session actually carried, which can legitimately be a personal or alternate
  -- address (EmployeeDashboard aliasEmails). Both are kept because they answer
  -- different questions: who this is, and how they got here.
  work_email      text not null,
  filed_by_email  text not null,
  member_name     text,
  -- Master-list Department cell as written, e.g. 'hsl:intake_specialist'.
  -- Stored RAW: this is a key, not a label (dept-label-display-sweep).
  department      text,

  -- Carla's Decision 4 list, 2026-09-15. Mirrored by SUPPORT_CATEGORIES in
  -- src/lib/support/types.ts; the two must be changed together.
  --
  -- Note what is absent: schedules and time-off. Carla ruled those "a manager
  -- question", so there is no category to file them under and the form steers
  -- instead. 'hours_time_adjustment' IS here, but only for asking about an
  -- adjustment that has ALREADY been approved — support is explicitly not a
  -- route for requesting one.
  category      text not null,
  constraint employee_support_tickets_category_valid check (
    category in (
      'pay_payslip',
      'bonus_pab',
      'hours_time_adjustment',
      'bank_payout',
      'documents_certificates',
      'gmail',
      'hubstaff',
      'roboform',
      'other'
    )
  ),

  -- What they actually wrote. This is the ticket's first message; replies live
  -- in employee_support_messages.
  concern       text not null,

  status        text not null default 'open',
  constraint employee_support_tickets_status_valid
    check (status in ('open', 'claimed', 'answered', 'closed')),

  -- Claiming is a compare-and-set: UPDATE ... WHERE claimed_by IS NULL. Two
  -- staffers cannot both take the same ticket; the loser gets zero rows back
  -- and the route answers 409 rather than silently overwriting.
  claimed_by    text,
  claimed_at    timestamptz,

  -- Stamped once, by the first staff reply. Never recomputed — it is the only
  -- evidence of how long the first answer took, and Carla's "within one working
  -- day" promise is measured against it if anyone ever chooses to measure it.
  first_response_at timestamptz,

  closed_by     text,
  closed_at     timestamptz,

  -- MODERATION — Carla asked us to "prescreen any hateful/hurtful language" and
  -- to flag "unprofessional behavior".
  --
  -- A flag NEVER blocks. Screening runs, records what it found, and the ticket
  -- is filed regardless. This is deliberate and load-bearing: a false positive
  -- on a blocking screen silences an employee with a real complaint, on the one
  -- channel the company built for complaints. Raising a flag to a refusal is a
  -- policy change, not a tuning knob, and belongs in the plan before the code.
  flagged_at    timestamptz,
  flag_reason   text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- A flag is an assertion and needs its reason; neither half alone is a state.
  constraint employee_support_tickets_flag_both_or_neither
    check ((flagged_at is null) = (flag_reason is null)),
  -- Claiming is one act, so both columns move together.
  constraint employee_support_tickets_claim_both_or_neither
    check ((claimed_at is null) = (claimed_by is null)),
  constraint employee_support_tickets_close_both_or_neither
    check ((closed_at is null) = (closed_by is null)),
  -- A closed ticket must carry its closure. The reverse is not asserted: a
  -- closed_at with a later reopen is a legitimate state this table allows.
  constraint employee_support_tickets_closed_has_stamp
    check (status <> 'closed' or closed_at is not null),
  -- A claimed ticket must name its claimant, or "claimed" means nothing.
  constraint employee_support_tickets_claimed_has_owner
    check (status <> 'claimed' or claimed_by is not null),
  constraint employee_support_tickets_work_email_present
    check (length(btrim(work_email)) > 0),
  constraint employee_support_tickets_filed_by_present
    check (length(btrim(filed_by_email)) > 0),
  -- An empty concern is a bug in the form, not a question.
  constraint employee_support_tickets_concern_present
    check (length(btrim(concern)) > 0),
  -- Matches the 4000-char clamp the route applies. The DB is the backstop, not
  -- the validator.
  constraint employee_support_tickets_concern_bounded
    check (length(concern) <= 4000)
);

comment on table public.employee_support_tickets is
  'Employee-filed support questions. Answered from /tickets -> Employee Support by the employee_support feature key. Service-role only; deliberately NOT in supabase_realtime.';

create unique index if not exists employee_support_tickets_no_uniq
  on public.employee_support_tickets (ticket_no);

-- The employee side always reads "my tickets, newest first".
create index if not exists employee_support_tickets_mine_idx
  on public.employee_support_tickets (lower(work_email), created_at desc);

-- The staff side's default view is "needs a reply, oldest first" — the
-- longest-waiting unanswered question, not the newest one.
create index if not exists employee_support_tickets_open_idx
  on public.employee_support_tickets (created_at)
  where status in ('open', 'claimed');

create index if not exists employee_support_tickets_flagged_idx
  on public.employee_support_tickets (flagged_at desc)
  where flagged_at is not null;

-- ===========================================================================
-- Messages
-- ===========================================================================

create table if not exists public.employee_support_messages (
  id            uuid primary key default gen_random_uuid(),
  ticket_id     uuid not null
                references public.employee_support_tickets (id) on delete cascade,

  -- Which side of the conversation. Not derived from whether the author holds
  -- the feature key at read time: grants are revoked, and a reply must still
  -- read as staff a year later.
  author_side   text not null,
  constraint employee_support_messages_side_valid
    check (author_side in ('employee', 'staff')),

  author_email  text not null,
  author_name   text,
  body          text not null,

  -- Same rule as the ticket: records, never blocks.
  flagged_at    timestamptz,
  flag_reason   text,

  -- Immutable once posted, exactly like ticket_comments. No updated_at, and no
  -- edit or delete path in the UI: a support thread is a record of what was
  -- said, and an editable record answers a different question than this one.
  created_at    timestamptz not null default now(),

  constraint employee_support_messages_flag_both_or_neither
    check ((flagged_at is null) = (flag_reason is null)),
  constraint employee_support_messages_author_present
    check (length(btrim(author_email)) > 0),
  constraint employee_support_messages_body_present
    check (length(btrim(body)) > 0),
  constraint employee_support_messages_body_bounded
    check (length(body) <= 4000)
);

comment on table public.employee_support_messages is
  'Replies on an employee support ticket. Immutable once posted. Service-role only; deliberately NOT in supabase_realtime.';

create index if not exists employee_support_messages_thread_idx
  on public.employee_support_messages (ticket_id, created_at);

-- ===========================================================================
-- Normalising triggers
-- ===========================================================================

create or replace function public.employee_support_tickets_normalize()
returns trigger
language plpgsql
as $$
begin
  new.work_email     := lower(btrim(new.work_email));
  new.filed_by_email := lower(btrim(new.filed_by_email));
  new.claimed_by     := lower(nullif(btrim(coalesce(new.claimed_by, '')), ''));
  new.closed_by      := lower(nullif(btrim(coalesce(new.closed_by, '')), ''));
  new.department     := nullif(btrim(coalesce(new.department, '')), '');
  new.updated_at     := now();
  return new;
end;
$$;

drop trigger if exists employee_support_tickets_normalize_trg
  on public.employee_support_tickets;
create trigger employee_support_tickets_normalize_trg
  before insert or update on public.employee_support_tickets
  for each row execute function public.employee_support_tickets_normalize();

create or replace function public.employee_support_messages_normalize()
returns trigger
language plpgsql
as $$
begin
  new.author_email := lower(btrim(new.author_email));
  return new;
end;
$$;

drop trigger if exists employee_support_messages_normalize_trg
  on public.employee_support_messages;
create trigger employee_support_messages_normalize_trg
  before insert on public.employee_support_messages
  for each row execute function public.employee_support_messages_normalize();

-- ===========================================================================
-- RLS: on, with no policies
-- ===========================================================================
-- Every read and write goes through a gated route holding the service-role key.
-- No policy is the point: with RLS enabled and nothing granted, the anon key
-- reads nothing at all. This is the house pattern, and here it is also the
-- reason the feature is allowed to exist on this data.

alter table public.employee_support_tickets  enable row level security;
alter table public.employee_support_messages enable row level security;
