-- Gift Tracker → Orders: approved tenure gifts locked into a priced invoice.
--
-- Kane, 2026-09-23: "whatever gets approved … would go to the Orders right away
-- no matter which month", "there should be a price on that Invoice … on how many
-- was ordered", "a locking mechanism where we can lock in the orders and a PDF
-- will be built", and a locked order can be REOPENED.
-- Governing doc: docs/features/gift-tracker-orders.md
--
-- An OPEN order is not stored anywhere: it is an approved
-- employee_gift_shipping_details row that no LOCKED order holds. Only the lock
-- writes, and what it writes is a SNAPSHOT — item, size, unit price, ship-to —
-- so a later price edit in Gift items or an address edit can never change an
-- invoice that was already sent to a vendor.
--
-- Service-role only: RLS on, NO policies, NOT in supabase_realtime, and all three
-- functions are revoked from PUBLIC / anon / authenticated (Postgres grants
-- EXECUTE to PUBLIC by default, which on Supabase means the anon key).

-- ===========================================================================
-- Orders (one per lock)
-- ===========================================================================

create table if not exists public.gift_orders (
  id              uuid primary key default gen_random_uuid(),
  -- Human-facing invoice number, its own series.
  order_no        bigint generated by default as identity,

  status          text not null default 'locked',
  constraint gift_orders_status_valid check (status in ('locked', 'reopened')),

  locked_at       timestamptz not null default now(),
  locked_by       text not null,
  constraint gift_orders_locked_by_present check (length(btrim(locked_by)) > 0),

  -- Reopening KEEPS the row. Deleting is a separate, explicit act
  -- (gift_order_delete) whose audit entry carries the full snapshot.
  reopened_at     timestamptz,
  reopened_by     text,
  reopen_reason   text,
  constraint gift_orders_reopen_both_or_neither
    check ((reopened_at is null) = (reopened_by is null)),
  constraint gift_orders_reopened_has_stamp
    check ((status = 'reopened') = (reopened_at is not null)),

  -- Integer centavos. Never a float: a total is summed, and floats do not sum.
  total_centavos  bigint not null,
  constraint gift_orders_total_nonneg check (total_centavos >= 0),
  line_count      integer not null,
  constraint gift_orders_has_lines check (line_count > 0),

  -- The whole invoice model as it was locked. The PDF is rebuilt from THIS,
  -- never from the live catalog or the live submissions.
  snapshot        jsonb not null,
  constraint gift_orders_snapshot_object check (jsonb_typeof(snapshot) = 'object'),

  created_at      timestamptz not null default now()
);

comment on table public.gift_orders is
  'Gift Tracker Orders: one row per locked invoice. Snapshot is the invoice as locked. Reopen keeps the row. Service-role only; NOT in supabase_realtime.';

create unique index if not exists gift_orders_no_uniq on public.gift_orders (order_no);
create index if not exists gift_orders_locked_at_idx on public.gift_orders (locked_at desc);

alter table public.gift_orders enable row level security;

-- ===========================================================================
-- Lines (one per gift item per submission)
-- ===========================================================================

create table if not exists public.gift_order_lines (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null references public.gift_orders (id) on delete restrict,

  -- Deliberately NO foreign key to employee_gift_shipping_details: the invoice
  -- must survive that row being edited or (after a reopen) deleted. The route
  -- refuses to edit or delete a submission a LOCKED order holds.
  submission_id   uuid not null,
  personal_email  text not null,
  milestone_index integer not null,

  item            text not null,
  -- Size / variant as it prints on the invoice ('' when the item has none).
  size            text not null default '',
  unit_centavos   bigint not null,
  qty             integer not null default 1,

  -- Stamped when the order is reopened; the gift is then free to be locked again.
  released_at     timestamptz,

  constraint gift_order_lines_item_present check (length(btrim(item)) > 0),
  constraint gift_order_lines_unit_positive check (unit_centavos > 0),
  constraint gift_order_lines_qty_positive check (qty > 0),
  constraint gift_order_lines_milestone_positive check (milestone_index > 0)
);

comment on table public.gift_order_lines is
  'Gift Tracker Orders: invoice lines. At most ONE unreleased set of lines per submission (gift_order_lines_one_live_order). Service-role only.';

-- THE double-invoicing guard. A submission can sit on many REOPENED orders, but
-- on at most one live one. Keyed on (submission_id, item) because one
-- submission can send two items ("Tote Bag & Mug").
create unique index if not exists gift_order_lines_one_live_order
  on public.gift_order_lines (submission_id, item)
  where released_at is null;

create index if not exists gift_order_lines_order_idx on public.gift_order_lines (order_id);
create index if not exists gift_order_lines_live_submission_idx
  on public.gift_order_lines (submission_id) where released_at is null;

alter table public.gift_order_lines enable row level security;

-- ===========================================================================
-- Lock — atomic: every line lands or none does
-- ===========================================================================

create or replace function public.gift_order_lock(
  p_locked_by text,
  p_total_centavos bigint,
  p_snapshot jsonb,
  p_lines jsonb
) returns table (id uuid, order_no bigint)
language plpgsql
as $$
declare
  v_id uuid;
  v_no bigint;
  v_count integer;
  v_bad uuid;
begin
  v_count := coalesce(jsonb_array_length(p_lines), 0);
  if v_count = 0 then
    raise exception 'gift_order_empty' using errcode = 'P0001';
  end if;

  -- Re-checked HERE, under a row lock, not trusted from the browser: a
  -- submission that was returned, edited back to pending, or deleted since the
  -- screen loaded must not be invoiced.
  select l.submission_id into v_bad
    from jsonb_to_recordset(p_lines) as l(submission_id uuid)
    left join public.employee_gift_shipping_details d on d.id = l.submission_id
   where d.id is null or d.status is distinct from 'approved'
   limit 1;
  if v_bad is not null then
    raise exception 'gift_order_not_approved:%', v_bad using errcode = 'P0001';
  end if;

  perform 1 from public.employee_gift_shipping_details d
   where d.id in (select (x->>'submission_id')::uuid from jsonb_array_elements(p_lines) x)
   for update;

  insert into public.gift_orders (locked_by, total_centavos, line_count, snapshot)
  values (lower(btrim(p_locked_by)), p_total_centavos, v_count, p_snapshot)
  returning gift_orders.id, gift_orders.order_no into v_id, v_no;

  -- A submission already on a live order violates gift_order_lines_one_live_order
  -- and aborts the whole function, order row included.
  insert into public.gift_order_lines
    (order_id, submission_id, personal_email, milestone_index, item, size, unit_centavos, qty)
  select v_id, l.submission_id, lower(btrim(l.personal_email)), l.milestone_index,
         l.item, coalesce(l.size, ''), l.unit_centavos, coalesce(l.qty, 1)
    from jsonb_to_recordset(p_lines) as l(
      submission_id uuid, personal_email text, milestone_index integer,
      item text, size text, unit_centavos bigint, qty integer
    );

  -- The total is re-derived from the lines, never trusted from the caller.
  if (select coalesce(sum(unit_centavos * qty), 0) from public.gift_order_lines
       where order_id = v_id) <> p_total_centavos then
    raise exception 'gift_order_total_mismatch' using errcode = 'P0001';
  end if;

  return query select v_id, v_no;
end;
$$;

-- ===========================================================================
-- Reopen — the invoice is kept, its gifts go back to Open
-- ===========================================================================

create or replace function public.gift_order_reopen(
  p_order_id uuid,
  p_reopened_by text,
  p_reason text
) returns void
language plpgsql
as $$
begin
  update public.gift_orders
     set status = 'reopened',
         reopened_at = now(),
         reopened_by = lower(btrim(p_reopened_by)),
         reopen_reason = nullif(btrim(coalesce(p_reason, '')), '')
   where id = p_order_id and status = 'locked';
  if not found then
    raise exception 'gift_order_not_locked' using errcode = 'P0001';
  end if;

  update public.gift_order_lines
     set released_at = now()
   where order_id = p_order_id and released_at is null;
end;
$$;

-- ===========================================================================
-- Delete — Kane, 2026-09-23 ("Allow deleting please"). Removes the invoice and
-- its lines for good; a LOCKED order's gifts go back to Open because nothing
-- holds them any more. The route reads the whole row BEFORE calling this and
-- writes it (snapshot, lines, totals) to audit_log once the delete succeeds, so
-- the invoice stays traceable after the row is gone.
-- ===========================================================================

create or replace function public.gift_order_delete(p_order_id uuid)
returns void
language plpgsql
as $$
begin
  perform 1 from public.gift_orders where id = p_order_id for update;
  if not found then
    raise exception 'gift_order_not_found' using errcode = 'P0001';
  end if;
  delete from public.gift_order_lines where order_id = p_order_id;
  delete from public.gift_orders where id = p_order_id;
end;
$$;

revoke all on function public.gift_order_lock(text, bigint, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.gift_order_reopen(uuid, text, text) from public, anon, authenticated;
revoke all on function public.gift_order_delete(uuid) from public, anon, authenticated;
grant execute on function public.gift_order_lock(text, bigint, jsonb, jsonb) to service_role;
grant execute on function public.gift_order_reopen(uuid, text, text) to service_role;
grant execute on function public.gift_order_delete(uuid) to service_role;
