-- ============================================================
-- Screening · table + upload-archive + active view (change-detection model)
-- ============================================================
-- The "Screenings2.0" tab of the "HR SCREENING 1.0" Google Sheet is the source
-- of truth; a manual "Sync from Google Sheet" button pulls it into these tables.
--
-- Because the sheet is large (~50k rows), the sync does CHANGE DETECTION rather
-- than rewriting every row each time:
--   - Each sheet row gets a `row_hash` (fingerprint of its mapped columns).
--   - On sync we compare hashes: INSERT new rows, UPDATE only genuinely-changed
--     rows, reactivate rows that reappeared, and set is_active=FALSE on rows that
--     dropped off the sheet. UNCHANGED rows get ZERO writes.
--   - `active_screening` = rows where is_active = TRUE (the current sheet state).
--     (This replaces the older "row tagged with the current upload" snapshot,
--     which forced a write per row per sync.)
--   - `screening_uploads` remains a per-sync audit log; is_current marks the
--     latest sync.
--
-- Match key = LOWER(TRIM("Email Address")); rows with no email are keyed by their
-- content hash instead. Ordering key = `grid_id` (the sheet's own monotonic
-- "Grid ID" column) so the board shows the latest-scanned people first.
--
-- Sheet columns synced (left → right, anchored on "Name"; "Team" before Name and
-- "Grid ID"/blank trailing columns are ignored for DISPLAY). The sheet has a
-- blank-header column between "Scheduled" and "2nd Interviewer" holding the
-- scheduled date → captured as "Scheduled Date". Two columns titled "Remarks" →
-- disambiguated positionally into "Initial Remarks" and "Remarks 2".
-- (Keep in sync with src/lib/screening/columns.ts.)
--
-- Idempotent — safe to re-run. Run as the Supabase service role / an SQL editor
-- session that can create tables & views in `public`.
-- ============================================================

-- ─── 1. Upload archive (per-sync audit log) ───────────────────
CREATE TABLE IF NOT EXISTS public.screening_uploads (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file  text,
  uploaded_at  timestamptz NOT NULL DEFAULT now(),
  uploaded_by  text,
  row_count    integer,
  is_current   boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS screening_uploads_one_current_idx
  ON public.screening_uploads (is_current)
  WHERE is_current = true;

CREATE INDEX IF NOT EXISTS screening_uploads_uploaded_at_idx
  ON public.screening_uploads (uploaded_at DESC);

-- ─── 2. Screening table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.screening (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id       bigint,        -- upload that last wrote this row
  source_file           text,
  first_seen_upload_id  bigint,        -- sync that first inserted this row
  last_seen_upload_id   bigint,        -- sync that last WROTE it (insert/change/reactivate/remove)
  synced_at             timestamptz,
  row_hash              text,          -- fingerprint of the mapped columns → change detection
  is_active             boolean NOT NULL DEFAULT true,  -- present in the latest sheet? drives the active view
  grid_id               bigint,        -- the sheet's own "Grid ID" (monotonic) → "latest first" order
  "Name"                text,
  "Email Address"       text,
  "Screener"            text,
  "Date"                text,
  "Initial"             text,
  "Initial Remarks"     text,
  "Scheduled"           text,
  "Scheduled Date"      text,
  "2nd Interviewer"     text,
  "No Show"             text,
  "Remarks 2"           text,
  "Source"              text,
  "Referral"            text
);

-- Idempotent adds so re-running upgrades an already-created table in place.
ALTER TABLE public.screening
  ADD COLUMN IF NOT EXISTS row_hash          text,
  ADD COLUMN IF NOT EXISTS is_active         boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS grid_id           bigint,
  ADD COLUMN IF NOT EXISTS "Scheduled Date"  text;

-- One row per candidate email. Partial (skips blank emails, which are keyed by
-- content hash in the reconcile). The sync dedupes incoming rows by this same key
-- (last-wins) so a duplicate email in the sheet never trips the index.
CREATE UNIQUE INDEX IF NOT EXISTS screening_email_uniq
  ON public.screening (lower(trim("Email Address")))
  WHERE "Email Address" IS NOT NULL AND trim("Email Address") <> '';

-- Fast active-set scan + latest-first ordering.
CREATE INDEX IF NOT EXISTS screening_is_active_idx ON public.screening (is_active) WHERE is_active;
CREATE INDEX IF NOT EXISTS screening_grid_id_idx   ON public.screening (grid_id DESC NULLS LAST);

-- ─── 3. Row-level security ────────────────────────────────────
-- This board holds candidate PII (names, emails). Enable RLS with NO policies so
-- the public API roles (anon/authenticated) get ZERO rows even if Supabase's
-- default privileges granted them SELECT. The service_role key used by
-- /api/screening has BYPASSRLS, so the app still reads/writes everything.
-- Idempotent — enabling already-enabled RLS is a no-op.
ALTER TABLE public.screening         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.screening_uploads ENABLE ROW LEVEL SECURITY;

-- ─── 4. Active view ───────────────────────────────────────────
-- The board = whatever is currently present in the sheet (is_active = true).
-- security_invoker = true → the view runs as the CALLING role, inheriting the
-- base-table RLS above (a default view runs as owner and would leak PII past RLS).
-- Requires Postgres 15+, which Supabase is. Drop+recreate so column changes (e.g.
-- the new "Scheduled Date") propagate on re-runs — SELECT * freezes the column
-- list at view-creation time.
DROP VIEW IF EXISTS public.active_screening;
CREATE VIEW public.active_screening WITH (security_invoker = true) AS
SELECT *
FROM public.screening
WHERE is_active = true;

-- ─── 5. Grants ────────────────────────────────────────────────
-- On a standard Supabase project the service_role already has full access to new
-- public objects via default privileges, so these explicit grants are usually
-- redundant. Wrapped in an exception guard so a SQL-editor role that lacks GRANT
-- rights on service_role can't fail the whole migration. Deliberately NOT granting
-- anon/authenticated — the RLS above protects the PII; the read path is the
-- service role only.
DO $$
BEGIN
  BEGIN
    GRANT SELECT                         ON public.active_screening  TO service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.screening         TO service_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.screening_uploads TO service_role;
  EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'Skipped explicit service_role grants (relying on Supabase default privileges): %', SQLERRM;
  END;
END $$;

-- ─── 6. Verify ────────────────────────────────────────────────
-- Before the first sync both are 0 / no current upload (correct empty state).
-- After a sync, active_view_count = number of rows currently in the sheet.
SELECT id, source_file, uploaded_at, row_count, is_current
FROM public.screening_uploads
ORDER BY uploaded_at DESC
LIMIT 5;

SELECT
  (SELECT count(*) FROM public.screening)        AS total_rows_all_time,
  (SELECT count(*) FROM public.active_screening) AS active_view_count;
