-- Global Master List — canonical employee directory (matches NEXT_PUBLIC_SUPABASE_EMPLOYEES_TABLE default).
-- Run in Supabase → SQL Editor after reviewing your project.
--
-- CSV import layout: rows 1–2 must contain the text MASTERLIST; row 3 = headers; row 4+ = data
-- (see validateMasterListCsvLayout in src/lib/supabase/global-master-list-db.ts).
-- The app reads: Department, Name, Personal Email, Work Email, Start Date, Profile Photo URL (optional).
-- `id` is required for legacy imports without batching (batched deletes).
-- `import_batch_id` + `source_file`: each CSV upload clears the table then inserts (full replace);
-- the app still sets these columns for auditing and consistent reads.

CREATE TABLE IF NOT EXISTS public.global_master_list (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id bigint,
  source_file text,
  "Department" text,
  "Name" text,
  "Personal Email" text,
  "Work Email" text,
  "Start Date" text,
  "Profile Photo URL" text
);

CREATE INDEX IF NOT EXISTS global_master_list_import_batch_id_idx
  ON public.global_master_list (import_batch_id DESC);

COMMENT ON TABLE public.global_master_list IS 'HR master roster; each CSV upload replaces all rows (single active roster).';

-- Existing deployments: add columns and backfill so every row belongs to batch 1 before new uploads.
-- ALTER TABLE public.global_master_list ADD COLUMN IF NOT EXISTS import_batch_id bigint;
-- ALTER TABLE public.global_master_list ADD COLUMN IF NOT EXISTS source_file text;
-- UPDATE public.global_master_list SET import_batch_id = 1, source_file = COALESCE(source_file, 'legacy')
--   WHERE import_batch_id IS NULL;
